require('dotenv').config()
const mongoose = require('mongoose')
const Product = require('./models/Product')

const newProducts = [
  // ── RESTAURATION (composites & flows) ────────────────────────
  { name: { fr: 'Palfique LX5', en: 'Palfique LX5' }, brand: 'Tokuyama', category: 'restauration', price: 300, images: [], description: { fr: "Composite universel Palfique LX5 Tokuyama, haute résistance à l'usure et excellente esthétique naturelle.", en: 'Palfique LX5 Tokuyama universal composite, high wear resistance and excellent natural aesthetics.' }, featured: false, inStock: true },
  { name: { fr: 'Filtek P60', en: 'Filtek P60' }, brand: '3M', category: 'restauration', price: 340, images: [], description: { fr: 'Composite postérieur 3M Filtek P60, haute résistance mécanique, idéal pour restaurations de classe I et II.', en: '3M Filtek P60 posterior composite, high mechanical resistance, ideal for class I and II restorations.' }, featured: false, inStock: true },
  { name: { fr: 'Solar X', en: 'Solar X' }, brand: 'GC', category: 'restauration', price: 280, images: [], description: { fr: 'Composite microhybride Solar X GC, polyvalent pour restaurations antérieures et postérieures.', en: 'GC Solar X microhybrid composite, versatile for anterior and posterior restorations.' }, featured: false, inStock: true },
  { name: { fr: 'Te Économe', en: 'Te Economique' }, brand: 'Ivoclar', category: 'restauration', price: 180, images: [], description: { fr: 'Composite universel Te Économe Ivoclar, rapport qualité-prix optimal pour restaurations directes.', en: 'Ivoclar Te Economique universal composite, optimal value for direct restorations.' }, featured: false, inStock: true },
  { name: { fr: 'Denfil', en: 'Denfil' }, brand: 'Denfil', category: 'restauration', price: 200, images: [], description: { fr: 'Composite microhybride Denfil, haute résistance et bonne finissabilité pour restaurations directes.', en: 'Denfil microhybrid composite, high resistance and good polishability for direct restorations.' }, featured: false, inStock: true },
  { name: { fr: 'Megafil', en: 'Megafil' }, brand: 'Sans Marque', category: 'restauration', price: 220, images: [], description: { fr: 'Composite universel Megafil, formule équilibrée pour restaurations antérieures et postérieures.', en: 'Megafil universal composite, balanced formula for anterior and posterior restorations.' }, featured: false, inStock: true },
  { name: { fr: 'IPS Empress Direct', en: 'IPS Empress Direct' }, brand: 'Ivoclar', category: 'restauration', price: 280, images: [], description: { fr: 'Composite universel IPS Empress Direct Ivoclar, fluorescence naturelle et polissabilité exceptionnelle.', en: 'IPS Empress Direct Ivoclar universal composite, natural fluorescence and exceptional polishability.' }, featured: false, inStock: true },
  { name: { fr: 'Tetric Bulk Fill', en: 'Tetric Bulk Fill' }, brand: 'Ivoclar', category: 'restauration', price: 260, images: [], description: { fr: "Composite bulk-fill Tetric Ivoclar, polymérisation en une couche jusqu'à 4 mm, faible contraction.", en: 'Tetric Ivoclar bulk-fill composite, single-layer polymerization up to 4 mm, low shrinkage.' }, featured: false, inStock: true },
  { name: { fr: 'Filtek Z350 XT', en: 'Filtek Z350 XT' }, brand: '3M', category: 'restauration', price: 350, images: [], description: { fr: "Composite nanocharge universel 3M Filtek Z350 XT, esthétique supérieure et excellente résistance à l'usure.", en: '3M Filtek Z350 XT nanofilled universal composite, superior aesthetics and excellent wear resistance.' }, featured: false, inStock: true },
  { name: { fr: 'Z350 Flow', en: 'Z350 Flow' }, brand: '3M', category: 'restauration', price: 340, images: [], description: { fr: 'Composite fluide nanocharge 3M Filtek Z350 XT Flow, adaptation marginale parfaite et haute esthétique.', en: '3M Filtek Z350 XT Flow nanofilled flowable composite, perfect marginal adaptation and high aesthetics.' }, featured: false, inStock: true },
  { name: { fr: 'Gradia Flow', en: 'Gradia Flow' }, brand: 'GC', category: 'restauration', price: 290, images: [], description: { fr: 'Composite fluide microhybride Gradia Flow GC, haute fluidité et résistance à la déformation.', en: 'GC Gradia Flow microhybrid flowable composite, high fluidity and deformation resistance.' }, featured: false, inStock: true },
  { name: { fr: 'Tetric N Flow', en: 'Tetric N Flow' }, brand: 'Ivoclar', category: 'restauration', price: 240, images: [], description: { fr: 'Composite fluide nano-hybride Tetric N-Flow Ivoclar, faible contraction de polymérisation.', en: 'Tetric N-Flow Ivoclar nano-hybrid flowable composite, low polymerization shrinkage.' }, featured: false, inStock: true },
  { name: { fr: 'Flow D Line', en: 'Flow D Line' }, brand: 'D Line', category: 'restauration', price: 190, images: [], description: { fr: 'Composite fluide Flow D Line, bonne fluidité pour cavités rétentives et points de contact.', en: 'D Line Flow flowable composite, good fluidity for retentive cavities and contact points.' }, featured: false, inStock: true },
  { name: { fr: 'I-Flow', en: 'I-Flow' }, brand: 'I Dental', category: 'restauration', price: 190, images: [], description: { fr: "Composite fluide I-Flow I Dental, adapté aux restaurations minimales et zones de difficile accès.", en: 'I-Flow I Dental flowable composite, suitable for minimal restorations and hard-to-reach areas.' }, featured: false, inStock: true },
  { name: { fr: 'Compoflow', en: 'Compoflow' }, brand: 'Sans Marque', category: 'restauration', price: 180, images: [], description: { fr: 'Composite fluide Compoflow universel, excellente maniabilité et bonne adaptation aux parois.', en: 'Compoflow universal flowable composite, excellent handling and good wall adaptation.' }, featured: false, inStock: true },
  { name: { fr: 'Compomax', en: 'Compomax' }, brand: 'D Tech', category: 'restauration', price: 220, images: [], description: { fr: 'Composite microhybride Compomax D Tech, haute résistance mécanique pour usage postérieur.', en: 'D Tech Compomax microhybrid composite, high mechanical resistance for posterior use.' }, featured: false, inStock: true },
  { name: { fr: 'Bisco Micro Esthetic', en: 'Bisco Micro Esthetic' }, brand: 'Bisco', category: 'restauration', price: 300, images: [], description: { fr: "Composite microhybride Bisco Micro Esthetic, haute polissabilité et esthétique naturelle pour dents antérieures.", en: 'Bisco Micro Esthetic microhybrid composite, high polishability and natural aesthetics for anterior teeth.' }, featured: false, inStock: true },
  { name: { fr: 'Bisco Nano Fil Unique', en: 'Bisco Nano Fil Unique' }, brand: 'Bisco', category: 'restauration', price: 320, images: [], description: { fr: 'Composite nano-hybride Bisco Nano Fil Unique, teinte universelle A2 pour restaurations directes tout usage.', en: 'Bisco Nano Fil Unique nano-hybrid composite, universal shade A2 for all-purpose direct restorations.' }, featured: false, inStock: true },
  { name: { fr: 'Bisco Nano Fil Flow', en: 'Bisco Nano Fil Flow' }, brand: 'Bisco', category: 'restauration', price: 300, images: [], description: { fr: 'Composite fluide nanocharge Bisco Nano Fil Flow, excellente adaptation aux parois et zones de difficile accès.', en: 'Bisco Nano Fil Flow nanofilled flowable composite, excellent wall adaptation for hard-to-reach areas.' }, featured: false, inStock: true },
  { name: { fr: 'Bisco Bulk Fil', en: 'Bisco Bulk Fil' }, brand: 'Bisco', category: 'restauration', price: 280, images: [], description: { fr: "Composite bulk-fill Bisco, obturation postérieure en une seule couche de 4 mm, faible contraction.", en: 'Bisco bulk-fill composite, single-layer 4 mm posterior filling, low shrinkage.' }, featured: false, inStock: true },
  { name: { fr: 'Bisco Nano Fil N', en: 'Bisco Nano Fil N' }, brand: 'Bisco', category: 'restauration', price: 320, images: [], description: { fr: "Composite nanocharge Bisco Nano Fil N, résistance à l'usure améliorée pour restaurations postérieures.", en: 'Bisco Nano Fil N nanofilled composite, improved wear resistance for posterior restorations.' }, featured: false, inStock: true },
  { name: { fr: 'Bisco Micro Esthetic Gingiva', en: 'Bisco Micro Esthetic Gingiva' }, brand: 'Bisco', category: 'restauration', price: 300, images: [], description: { fr: 'Composite Bisco Micro Esthetic Gingiva, teinte gingivale pour reconstruction esthétique des tissus mous.', en: 'Bisco Micro Esthetic Gingiva composite, gingival shade for aesthetic soft tissue reconstruction.' }, featured: false, inStock: true },

  // ── RECONSTITUTION (adhésifs) ────────────────────────────────
  { name: { fr: 'Adhésif Single Bond 2', en: 'Single Bond 2 Adhesive' }, brand: '3M', category: 'reconstitution', price: 520, images: [], description: { fr: "Adhésif mono-composant 3M Scotchbond Single Bond 2, mordançage total, excellente résistance à la liaison.", en: '3M Scotchbond Single Bond 2 single-component adhesive, total-etch, excellent bond strength.' }, featured: false, inStock: true },
  { name: { fr: 'Adhésif G Premio Bond', en: 'G Premio Bond Adhesive' }, brand: 'GC', category: 'reconstitution', price: 620, images: [], description: { fr: 'Adhésif universel G Premio Bond GC, compatible avec toutes les stratégies de mordançage.', en: 'GC G Premio Bond universal adhesive, compatible with all etching strategies.' }, featured: false, inStock: true },
  { name: { fr: 'Adhésif Solare Universal Bond', en: 'Solare Universal Bond Adhesive' }, brand: 'GC', category: 'reconstitution', price: 580, images: [], description: { fr: "Adhésif universel Solare Universal Bond GC, liaison fiable à l'émail, dentine et substrats indirects.", en: 'GC Solare Universal Bond adhesive, reliable bond to enamel, dentin and indirect substrates.' }, featured: false, inStock: true },
  { name: { fr: 'Adhésif Tetric N Bond', en: 'Tetric N Bond Adhesive' }, brand: 'Ivoclar', category: 'reconstitution', price: 420, images: [], description: { fr: "Adhésif bi-composant Tetric N-Bond Ivoclar, mordançage total, forte adhésion à l'émail et dentine.", en: 'Tetric N-Bond Ivoclar two-component adhesive, total-etch, strong adhesion to enamel and dentin.' }, featured: false, inStock: true },
  { name: { fr: 'Adhésif All Bond Universal', en: 'All Bond Universal Adhesive' }, brand: 'Bisco', category: 'reconstitution', price: 680, images: [], description: { fr: 'Adhésif universel All Bond Universal Bisco, compatible méthode directe et indirecte, toutes stratégies.', en: 'Bisco All Bond Universal adhesive, compatible with direct and indirect methods, all strategies.' }, featured: false, inStock: true },
  { name: { fr: 'Adhésif Z Prime Plus', en: 'Z Prime Plus Adhesive' }, brand: 'Bisco', category: 'reconstitution', price: 450, images: [], description: { fr: 'Primaire de liaison Bisco Z Prime Plus, adhésion aux métaux, zircone et alumine sans sablage.', en: 'Bisco Z Prime Plus bonding primer, adhesion to metals, zirconia and alumina without sandblasting.' }, featured: false, inStock: true },
  { name: { fr: 'Adhésif Te Économe Bond', en: 'Te Economique Bond Adhesive' }, brand: 'Ivoclar', category: 'reconstitution', price: 350, images: [], description: { fr: "Adhésif Te Économe Bond Ivoclar, formule économique avec bonne résistance d'adhésion.", en: 'Ivoclar Te Economique Bond adhesive, economical formula with good bond strength.' }, featured: false, inStock: true },
  { name: { fr: 'Monobond Plus', en: 'Monobond Plus' }, brand: 'Ivoclar', category: 'reconstitution', price: 580, images: [], description: { fr: 'Silane et primaire universel Monobond Plus Ivoclar, traitement de surface pour restaurations céramiques et métalliques.', en: 'Monobond Plus Ivoclar universal silane and primer, surface treatment for ceramic and metal restorations.' }, featured: false, inStock: true },
  { name: { fr: 'Adhésif D Line Bond', en: 'D Line Bond Adhesive' }, brand: 'D Line', category: 'reconstitution', price: 280, images: [], description: { fr: 'Adhésif D Line Bond, agent de liaison universel économique pour restaurations composites directes.', en: 'D Line Bond adhesive, economical universal bonding agent for direct composite restorations.' }, featured: false, inStock: true },

  // ── RECONSTITUTION (acides & conditionneurs) ─────────────────
  { name: { fr: 'Ultra Etch', en: 'Ultra Etch' }, brand: 'Ultradent', category: 'reconstitution', price: 320, images: [], description: { fr: 'Gel de mordançage Ultra Etch Ultradent, acide phosphorique 35%, consistance stable et rinçage facile.', en: 'Ultradent Ultra Etch etching gel, 35% phosphoric acid, stable consistency and easy rinsing.' }, featured: false, inStock: true },
  { name: { fr: 'Dentaflux Acide 60g', en: 'Dentaflux Acid 60g' }, brand: 'Dentaflux', category: 'reconstitution', price: 120, images: [], description: { fr: "Gel d'acide phosphorique 37% Dentaflux 60g, mordançage émail et dentine, conditionnement économique.", en: 'Dentaflux 60g 37% phosphoric acid gel, enamel and dentin etching, economical packaging.' }, featured: false, inStock: true },
  { name: { fr: 'I Gel', en: 'I Gel' }, brand: 'I Dental', category: 'reconstitution', price: 150, images: [], description: { fr: "Gel de mordançage I Gel, acide phosphorique pour conditionnement de l'émail et de la dentine.", en: 'I Gel etching gel, phosphoric acid for conditioning enamel and dentin.' }, featured: false, inStock: true },
  { name: { fr: 'Porcelain Etch avec Silane', en: 'Porcelain Etch with Silane' }, brand: 'Sans Marque', category: 'reconstitution', price: 280, images: [], description: { fr: 'Kit de conditionnement porcelaine avec acide fluorhydrique et silane, pour collage optimal des facettes.', en: 'Porcelain conditioning kit with hydrofluoric acid and silane, for optimal veneer bonding.' }, featured: false, inStock: true },
  { name: { fr: 'Porcelain Etch sans Silane', en: 'Porcelain Etch without Silane' }, brand: 'Sans Marque', category: 'reconstitution', price: 220, images: [], description: { fr: "Gel de mordançage porcelaine à l'acide fluorhydrique, préparation de surface avant collage céramique.", en: 'Porcelain hydrofluoric acid etching gel, surface preparation before ceramic bonding.' }, featured: false, inStock: true },
  { name: { fr: 'Condac Porcelana', en: 'Condac Porcelana' }, brand: 'FGM', category: 'reconstitution', price: 320, images: [], description: { fr: 'Gel conditionneur pour porcelaine Condac FGM, acide fluorhydrique 10% pour traitement de surface céramique.', en: 'Condac Porcelana FGM porcelain conditioner, 10% hydrofluoric acid for ceramic surface treatment.' }, featured: false, inStock: true },
  { name: { fr: 'Prosil', en: 'Prosil' }, brand: 'Sans Marque', category: 'reconstitution', price: 280, images: [], description: { fr: 'Agent silane Prosil pour traitement de surface des restaurations céramiques avant collage.', en: 'Prosil silane agent for ceramic restoration surface treatment before bonding.' }, featured: false, inStock: true },

  // ── RECONSTITUTION (temporaires) ────────────────────────────
  { name: { fr: 'Acrytemp', en: 'Acrytemp' }, brand: 'Sans Marque', category: 'reconstitution', price: 350, images: [], description: { fr: 'Résine acrylique autopolymérisante Acrytemp pour prothèses provisoires, bonne esthétique et résistance.', en: 'Acrytemp self-curing acrylic resin for temporary prostheses, good aesthetics and resistance.' }, featured: false, inStock: true },
  { name: { fr: 'Bright Temporary', en: 'Bright Temporary' }, brand: 'Sans Marque', category: 'reconstitution', price: 380, images: [], description: { fr: 'Composite bis-acryl Bright Temporary pour couronnes et bridges provisoires esthétiques.', en: 'Bright Temporary bis-acryl composite for aesthetic temporary crowns and bridges.' }, featured: false, inStock: true },
  { name: { fr: 'Unifast 3', en: 'Unifast 3' }, brand: 'GC', category: 'reconstitution', price: 480, images: [], description: { fr: 'Résine autopolymérisable Unifast 3 GC pour prothèses provisoires, teintes stables et polissage aisé.', en: 'GC Unifast 3 self-curing resin for temporary prostheses, stable shades and easy polishing.' }, featured: false, inStock: true },
  { name: { fr: 'Visalys Temp', en: 'Visalys Temp' }, brand: 'Kettenbach', category: 'reconstitution', price: 650, images: [], description: { fr: 'Composite bis-acryl Visalys Temp Kettenbach, restaurations temporaires haute esthétique, translucidité naturelle.', en: 'Kettenbach Visalys Temp bis-acryl composite, high-aesthetic temporary restorations, natural translucency.' }, featured: false, inStock: true },

  // ── RECONSTITUTION (Bisco & matériaux de reconstitution) ─────
  { name: { fr: 'Bisco Porcelain Etchant', en: 'Bisco Porcelain Etchant' }, brand: 'Bisco', category: 'reconstitution', price: 280, images: [], description: { fr: 'Gel de mordançage pour porcelaine Bisco, acide fluorhydrique 9.5% pour conditionnement des céramiques.', en: 'Bisco porcelain etching gel, 9.5% hydrofluoric acid for ceramic conditioning.' }, featured: false, inStock: true },
  { name: { fr: 'Uni Etch', en: 'Uni Etch' }, brand: 'Bisco', category: 'reconstitution', price: 200, images: [], description: { fr: "Gel d'acide phosphorique Uni Etch Bisco, mordançage sélectif de l'émail, consistance optimale.", en: 'Bisco Uni Etch phosphoric acid gel, selective enamel etching, optimal consistency.' }, featured: false, inStock: true },
  { name: { fr: 'Dentocore Body', en: 'Dentocore Body' }, brand: 'Itena', category: 'reconstitution', price: 380, images: [], description: { fr: 'Composite de reconstruction coronaire Dentocore Body Itena, dual-cure, haute résistance mécanique.', en: 'Itena Dentocore Body core build-up composite, dual-cure, high mechanical resistance.' }, featured: false, inStock: true },
  { name: { fr: 'Core Flo DC', en: 'Core Flo DC' }, brand: 'Bisco', category: 'reconstitution', price: 420, images: [], description: { fr: 'Composite fluide de reconstruction Core Flo DC Bisco, injection directe, dual-cure, pour fixation tenon.', en: 'Bisco Core Flo DC flowable build-up composite, direct injection, dual-cure, for post retention.' }, featured: false, inStock: true },
  { name: { fr: 'All Cem Core', en: 'All Cem Core' }, brand: 'FGM', category: 'reconstitution', price: 350, images: [], description: { fr: 'Composite de reconstruction coronaire All Cem Core FGM, dual-cure, radio-opaque, bonne résistance.', en: 'FGM All Cem Core build-up composite, dual-cure, radiopaque, good resistance.' }, featured: false, inStock: true },
  { name: { fr: 'Gradia Core', en: 'Gradia Core' }, brand: 'GC', category: 'reconstitution', price: 450, images: [], description: { fr: 'Composite de reconstruction coronaire Gradia Core GC, haute résistance à la compression, teinte universelle.', en: 'GC Gradia Core build-up composite, high compression resistance, universal shade.' }, featured: false, inStock: true },
  { name: { fr: 'Repo Core DC', en: 'Repo Core DC' }, brand: 'Bisco', category: 'reconstitution', price: 480, images: [], description: { fr: "Composite de reconstitution coronaire Repo Core DC Bisco, dual-cure, excellente adhésion à la dentine.", en: 'Bisco Repo Core DC build-up composite, dual-cure, excellent dentin adhesion.' }, featured: false, inStock: true },
  { name: { fr: 'Tenon Fibre Itena', en: 'Itena Fiber Post' }, brand: 'Itena', category: 'reconstitution', price: 160, images: [], description: { fr: 'Tenons en fibre de verre Itena, translucides, haute résistance à la flexion, conducteurs de lumière.', en: 'Itena glass fiber posts, translucent, high flexural strength, light-conducting.' }, featured: false, inStock: true },
  { name: { fr: 'Tenon Fibre Vivadent', en: 'Vivadent Fiber Post' }, brand: 'Ivoclar', category: 'reconstitution', price: 200, images: [], description: { fr: "Tenons en fibre de verre Ivoclar Vivadent, module d'élasticité proche de la dentine, biocompatible.", en: 'Ivoclar Vivadent glass fiber posts, elastic modulus close to dentin, biocompatible.' }, featured: false, inStock: true },
  { name: { fr: 'Tenon Fibre Post', en: 'Fiber Post' }, brand: 'Sans Marque', category: 'reconstitution', price: 120, images: [], description: { fr: 'Tenons en fibre de verre, forte résistance à la traction, conditionnement économique.', en: 'Glass fiber posts, high tensile strength, economical packaging.' }, featured: false, inStock: true },
  { name: { fr: 'Tenon Fibre Post 3M', en: '3M Fiber Post' }, brand: '3M', category: 'reconstitution', price: 220, images: [], description: { fr: "Tenons en fibre 3M RelyX Fiber Post, surface rugueuse pour adhésion optimale du ciment de scellement.", en: '3M RelyX Fiber Post, rough surface for optimal cement adhesion.' }, featured: false, inStock: true },
  { name: { fr: 'Foret Largo', en: 'Largo Drill' }, brand: 'Sans Marque', category: 'reconstitution', price: 80, images: [], description: { fr: "Forets Largo pour élargissement et mise en forme du canal radiculaire avant pose de tenon.", en: 'Largo drills for root canal enlargement and shaping before post placement.' }, featured: false, inStock: true },
  { name: { fr: 'Foret Gates', en: 'Gates-Glidden Drill' }, brand: 'Sans Marque', category: 'reconstitution', price: 75, images: [], description: { fr: "Forets Gates-Glidden acier inoxydable, élargissement de l'entrée canalaire et du tiers coronaire.", en: 'Stainless steel Gates-Glidden drills, canal orifice and coronal third enlargement.' }, featured: false, inStock: true },
  { name: { fr: 'Choice 2 Kit', en: 'Choice 2 Kit' }, brand: 'Bisco', category: 'reconstitution', price: 1500, images: [], description: { fr: 'Kit de collage de facettes Choice 2 Bisco, ciment résine photopolymérisable, multiples teintes et opacités.', en: 'Bisco Choice 2 veneer bonding kit, light-cured resin cement, multiple shades and opacities.' }, featured: false, inStock: true },
  { name: { fr: 'Intraoral Repair Kit', en: 'Intraoral Repair Kit' }, brand: 'Bisco', category: 'reconstitution', price: 850, images: [], description: { fr: 'Kit de réparation intra-orale Bisco, collage de facettes et réparations de céramiques directement en bouche.', en: 'Bisco intraoral repair kit, veneer bonding and ceramic repairs directly in the mouth.' }, featured: false, inStock: true },
  { name: { fr: 'Relyx Veneer', en: 'Relyx Veneer' }, brand: '3M', category: 'reconstitution', price: 1200, images: [], description: { fr: 'Ciment résine photopolymérisable Relyx Veneer 3M, haute translucidité, collage de facettes et inlays.', en: '3M Relyx Veneer light-cured resin cement, high translucency, for veneer and inlay bonding.' }, featured: false, inStock: true },
  { name: { fr: 'Variolink N', en: 'Variolink N' }, brand: 'Ivoclar', category: 'reconstitution', price: 1800, images: [], description: { fr: 'Système de collage Variolink N Ivoclar, dual-cure, pour facettes, couronnes et inlays céramiques.', en: 'Ivoclar Variolink N bonding system, dual-cure, for ceramic veneers, crowns and inlays.' }, featured: false, inStock: true },

  // ── FINITION & FRAISE (nouveaux) ────────────────────────────
  { name: { fr: 'Diamond Excel', en: 'Diamond Excel' }, brand: 'AT Dental', category: 'fraise', price: 450, images: [], description: { fr: 'Pâte de polissage diamantée Diamond Excel, finition composite en une étape, haute brillance durable.', en: 'Diamond Excel polishing paste, single-step composite finishing, long-lasting high shine.' }, featured: false, inStock: true },
  { name: { fr: 'Spectra', en: 'Spectra' }, brand: 'Dentsply', category: 'fraise', price: 380, images: [], description: { fr: 'Système de polissage Spectra, disques et cupules pour finition et polissage composite multi-étapes.', en: 'Spectra polishing system, discs and cups for multi-step composite finishing and polishing.' }, featured: false, inStock: true },
  { name: { fr: 'Dentaflux Pâte Prophylactique', en: 'Dentaflux Prophy Paste' }, brand: 'Dentaflux', category: 'fraise', price: 180, images: [], description: { fr: 'Pâte prophylactique Dentaflux pour détartrage et polissage coronaire, différentes granulométries.', en: 'Dentaflux prophylactic paste for scaling and coronal polishing, various granulometries.' }, featured: false, inStock: true },
  { name: { fr: 'Détartrex', en: 'Detartrex' }, brand: 'Septodont', category: 'fraise', price: 380, images: [], description: { fr: 'Pâte prophylactique Détartrex Septodont, élimination du tartre et polissage des surfaces dentaires.', en: 'Septodont Detartrex prophylactic paste, tartar removal and dental surface polishing.' }, featured: false, inStock: true },
  { name: { fr: 'Cavex Prophy Paste', en: 'Cavex Prophy Paste' }, brand: 'Cavex', category: 'fraise', price: 220, images: [], description: { fr: 'Pâte prophylactique Cavex, polissage dentaire fluoré, différentes textures disponibles.', en: 'Cavex prophylactic paste, fluoride dental polishing, various textures available.' }, featured: false, inStock: true },
  { name: { fr: 'Cupule Dochem', en: 'Dochem Polishing Cup' }, brand: 'Dochem', category: 'fraise', price: 60, images: [], description: { fr: 'Cupules de polissage Dochem en caoutchouc, montage sur contre-angle, finition des restaurations composites.', en: 'Dochem rubber polishing cups, contra-angle mount, composite restoration finishing.' }, featured: false, inStock: true },
  { name: { fr: 'Composite Polish Kit', en: 'Composite Polish Kit' }, brand: 'Sans Marque', category: 'fraise', price: 280, images: [], description: { fr: 'Kit de polissage composite complet, disques, cupules et pâte pour finition en plusieurs étapes.', en: 'Complete composite polishing kit, discs, cups and paste for multi-step finishing.' }, featured: false, inStock: true },
  { name: { fr: 'Kit Disque Tor', en: 'Tor Disc Kit' }, brand: 'Tor', category: 'fraise', price: 200, images: [], description: { fr: 'Kit de disques de polissage Tor, grains variables pour contourage et finition des restaurations composites.', en: 'Tor polishing disc kit, variable grits for contouring and finishing composite restorations.' }, featured: false, inStock: true },
  { name: { fr: 'Brossette de Polissage', en: 'Polishing Brush' }, brand: 'Sans Marque', category: 'fraise', price: 40, images: [], description: { fr: 'Brossettes de polissage pour contre-angle, nettoyage et polissage prophylactique des surfaces dentaires.', en: 'Polishing brushes for contra-angle, prophylactic cleaning and polishing of dental surfaces.' }, featured: false, inStock: true },
  { name: { fr: 'Cupule Jota', en: 'Jota Polishing Cup' }, brand: 'Jota', category: 'fraise', price: 80, images: [], description: { fr: 'Cupules de polissage Jota haute qualité, finition et brillance des restaurations composites.', en: 'Jota high-quality polishing cups, finishing and shine for composite restorations.' }, featured: false, inStock: true },
  { name: { fr: 'Fraise Horico', en: 'Horico Bur' }, brand: 'Horico', category: 'fraise', price: 180, images: [], description: { fr: 'Fraises Horico diamantées et carbure, gamme complète endo-z, zekrya, à os, haute précision de coupe.', en: 'Horico diamond and carbide burs, complete range endo-z, zekrya, bone burs, high cutting precision.' }, featured: false, inStock: true },

  // ── INSTRUMENTATION (nouveaux) ───────────────────────────────
  { name: { fr: 'Manches Miroirs', en: 'Mirror Handles' }, brand: 'Falcon', category: 'instrumentation', price: 80, images: [], description: { fr: 'Manches pour miroirs à bouche Falcon, acier inoxydable, prise ergonomique, autoclavables.', en: 'Falcon mouth mirror handles, stainless steel, ergonomic grip, autoclavable.' }, featured: false, inStock: true },
  { name: { fr: 'Sonde Dentaire', en: 'Dental Probe' }, brand: 'Falcon', category: 'instrumentation', price: 45, images: [], description: { fr: 'Sonde dentaire droite et courbée Falcon, acier inoxydable, pointe effilée pour exploration cavitaire.', en: 'Falcon straight and curved dental probe, stainless steel, tapered tip for cavity exploration.' }, featured: false, inStock: true },
  { name: { fr: 'Décolleur', en: 'Periosteal Elevator' }, brand: 'Falcon', category: 'instrumentation', price: 160, images: [], description: { fr: 'Décolleur périosté Falcon, lame fine pour décollement du périoste, acier inoxydable chirurgical.', en: 'Falcon periosteal elevator, thin blade for periosteum detachment, surgical stainless steel.' }, featured: false, inStock: true },
  { name: { fr: 'Curette', en: 'Curette' }, brand: 'Falcon', category: 'instrumentation', price: 95, images: [], description: { fr: 'Curette dentaire Falcon, détartrage et surfaçage radiculaire, différentes angulations disponibles.', en: 'Falcon dental curette, scaling and root planing, various angulations available.' }, featured: false, inStock: true },
  { name: { fr: 'Burnissoir', en: 'Burnisher' }, brand: 'Falcon', category: 'instrumentation', price: 95, images: [], description: { fr: 'Burnissoir Falcon pour lissage et adaptation des restaurations métalliques, acier inoxydable.', en: 'Falcon burnisher for smoothing and adapting metal restorations, stainless steel.' }, featured: false, inStock: true },
  { name: { fr: 'Spatule à Ciment', en: 'Cement Spatula' }, brand: 'Falcon', category: 'instrumentation', price: 65, images: [], description: { fr: 'Spatule à ciment Falcon double extrémité, mélange des biomatériaux et ciments dentaires.', en: 'Falcon double-ended cement spatula, mixing biomaterials and dental cements.' }, featured: false, inStock: true },
  { name: { fr: 'Spatule de Bouche', en: 'Mouth Spatula' }, brand: 'Falcon', category: 'instrumentation', price: 55, images: [], description: { fr: 'Spatule de bouche Falcon, manipulation des composites et matériaux plastiques en cavité buccale.', en: 'Falcon mouth spatula, handling composites and plastic materials in the oral cavity.' }, featured: false, inStock: true },
  { name: { fr: 'Râpe à Os', en: 'Bone File' }, brand: 'Falcon', category: 'instrumentation', price: 180, images: [], description: { fr: 'Râpe à os chirurgicale Falcon, régularisation des crêtes osseuses après extraction, acier inoxydable.', en: 'Falcon surgical bone file, regularizing bone ridges after extraction, stainless steel.' }, featured: false, inStock: true },
  { name: { fr: 'Castroviejo', en: 'Castroviejo Needle Holder' }, brand: 'Falcon', category: 'instrumentation', price: 220, images: [], description: { fr: 'Porte-aiguilles Castroviejo Falcon, précision maximale pour sutures chirurgicales fines, autoclavable.', en: 'Falcon Castroviejo needle holder, maximum precision for fine surgical sutures, autoclavable.' }, featured: false, inStock: true },
  { name: { fr: 'Plateaux Inox', en: 'Stainless Steel Trays' }, brand: 'Falcon', category: 'instrumentation', price: 120, images: [], description: { fr: 'Plateaux inox Falcon grand et petit format, présentation des instruments, robustes et autoclavables.', en: 'Falcon stainless steel trays large and small format, instrument presentation, robust and autoclavable.' }, featured: false, inStock: true },
  { name: { fr: 'Sonde Parodontale Graduée', en: 'Graduated Periodontal Probe' }, brand: 'Falcon', category: 'instrumentation', price: 120, images: [], description: { fr: 'Sonde parodontale graduée Falcon, mesure des poches parodontales, graduation au millimètre.', en: 'Falcon graduated periodontal probe, measuring periodontal pockets, millimeter graduation.' }, featured: false, inStock: true },
  { name: { fr: 'Élévateur à Racine', en: 'Root Elevator' }, brand: 'Falcon', category: 'instrumentation', price: 140, images: [], description: { fr: 'Élévateurs à racine Falcon, luxation et extraction des racines résiduelles, différentes formes disponibles.', en: 'Falcon root elevators, luxation and extraction of residual roots, various shapes available.' }, featured: false, inStock: true },
  { name: { fr: 'Chompret Syndesmotome', en: 'Syndesmotome' }, brand: 'Falcon', category: 'instrumentation', price: 130, images: [], description: { fr: 'Chompret et syndesmotome Falcon, section des fibres desmodontales avant extraction dentaire.', en: 'Falcon chompret and syndesmotome, severing desmodontal fibers before dental extraction.' }, featured: false, inStock: true },
  { name: { fr: 'Porte-aiguilles', en: 'Needle Holder' }, brand: 'Falcon', category: 'instrumentation', price: 180, images: [], description: { fr: "Porte-aiguilles chirurgical Falcon, maintien sécurisé des aiguilles pour sutures, acier inoxydable.", en: 'Falcon surgical needle holder, secure needle grip for suturing, stainless steel.' }, featured: false, inStock: true },
  { name: { fr: 'Pince Mathieu', en: 'Mathieu Pliers' }, brand: 'Falcon', category: 'instrumentation', price: 160, images: [], description: { fr: 'Pince Mathieu Falcon à cliquet, maintien des aiguilles et ligatures, blocage automatique.', en: 'Falcon Mathieu ratchet pliers, needle and ligature holding, automatic locking.' }, featured: false, inStock: true },
  { name: { fr: 'Précelle Mathieu', en: 'Mathieu Tweezers' }, brand: 'Falcon', category: 'instrumentation', price: 95, images: [], description: { fr: 'Précelle Mathieu Falcon, manipulation fine des fils de suture et ligatures, acier inoxydable.', en: 'Falcon Mathieu tweezers, fine manipulation of suture threads and ligatures, stainless steel.' }, featured: false, inStock: true },
  { name: { fr: 'Ciseau à Os', en: 'Bone Chisel' }, brand: 'Falcon', category: 'instrumentation', price: 220, images: [], description: { fr: "Ciseau à os chirurgical Falcon, ostéotomie et régularisation des crêtes osseuses, tranchant durable.", en: 'Falcon surgical bone chisel, osteotomy and bone ridge regularization, durable cutting edge.' }, featured: false, inStock: true },
  { name: { fr: 'Excavateur', en: 'Excavator' }, brand: 'Falcon', category: 'instrumentation', price: 75, images: [], description: { fr: 'Excavateur dentaire Falcon double extrémité, élimination de la dentine cariée, différentes tailles.', en: 'Falcon double-ended dental excavator, carious dentin removal, various sizes.' }, featured: false, inStock: true },
  { name: { fr: 'Fouloir', en: 'Condenser' }, brand: 'Falcon', category: 'instrumentation', price: 75, images: [], description: { fr: "Fouloir dentaire Falcon, condensation des amalgames et matériaux plastiques, embouts variés.", en: 'Falcon dental condenser, amalgam and plastic material condensation, various tips.' }, featured: false, inStock: true },

  // ── PETIT ÉQUIPEMENT (nouveaux) ──────────────────────────────
  { name: { fr: 'Moteur Endo Radar Pro', en: 'Radar Pro Endo Motor' }, brand: 'Woodpecker', category: 'petit-equipement', price: 8500, images: [], description: { fr: "Moteur endodontique Radar Pro Woodpecker, localisateur d'apex intégré, programmes NiTi préréglés.", en: 'Woodpecker Radar Pro endodontic motor, integrated apex locator, preset NiTi programs.' }, featured: false, inStock: true },
  { name: { fr: 'Moteur Endo C-SMART', en: 'C-SMART Endo Motor' }, brand: 'COXO', category: 'petit-equipement', price: 6500, images: [], description: { fr: "Moteur endodontique C-SMART COXO, localisateur d'apex intégré, léger et ergonomique, programmes configurables.", en: 'COXO C-SMART endodontic motor, integrated apex locator, lightweight and ergonomic, configurable programs.' }, featured: false, inStock: true },
  { name: { fr: 'Moteur Endo NSK DT', en: 'NSK DT Endo Motor' }, brand: 'NSK', category: 'petit-equipement', price: 9500, images: [], description: { fr: "Moteur endodontique NSK DT, haute précision couple et vitesse, localisateur d'apex intégré.", en: 'NSK DT endodontic motor, high torque and speed precision, integrated apex locator.' }, featured: false, inStock: true },
  { name: { fr: 'Moteur Endo Ionyx', en: 'Ionyx Endo Motor' }, brand: 'Ionyx', category: 'petit-equipement', price: 5500, images: [], description: { fr: "Moteur endodontique Ionyx sans fil, compact et léger, programmes NiTi multiples, facile d'utilisation.", en: 'Ionyx cordless endodontic motor, compact and lightweight, multiple NiTi programs, easy to use.' }, featured: false, inStock: true },
  { name: { fr: 'Lampe O-Light', en: 'O-Light Curing Lamp' }, brand: 'O-Light', category: 'petit-equipement', price: 7500, images: [], description: { fr: 'Lampe de photopolymérisation O-Light haute puissance, spectre large, minuterie et modes de polymérisation.', en: 'O-Light high-power curing lamp, wide spectrum, timer and curing modes.' }, featured: false, inStock: true },
  { name: { fr: 'Lampe COXO Nano', en: 'COXO Nano Curing Lamp' }, brand: 'COXO', category: 'petit-equipement', price: 1800, images: [], description: { fr: 'Lampe de photopolymérisation sans fil COXO Nano, ultra-compacte, 1500 mW/cm², légère et maniable.', en: 'COXO Nano cordless curing lamp, ultra-compact, 1500 mW/cm², lightweight and handy.' }, featured: false, inStock: true },
  { name: { fr: 'Lampe Valo X', en: 'Valo X Curing Lamp' }, brand: 'Ultradent', category: 'petit-equipement', price: 12000, images: [], description: { fr: 'Lampe de photopolymérisation Valo X Ultradent, technologie Polar Arc, 3200 mW/cm², polymérisation ultra-rapide.', en: 'Ultradent Valo X curing lamp, Polar Arc technology, 3200 mW/cm², ultra-fast polymerization.' }, featured: false, inStock: true },
  { name: { fr: 'Détartreur Max Piezo 7+', en: 'Max Piezo 7+ Scaler' }, brand: 'Max', category: 'petit-equipement', price: 3500, images: [], description: { fr: 'Détartreur piézoélectrique Max Piezo 7+, 7 inserts inclus, puissant et silencieux pour détartrage efficace.', en: 'Max Piezo 7+ piezoelectric scaler, 7 inserts included, powerful and quiet for effective scaling.' }, featured: false, inStock: true },
  { name: { fr: 'Turbine Apple Dent', en: 'Apple Dent Turbine' }, brand: 'Apple Dent', category: 'petit-equipement', price: 750, images: [], description: { fr: 'Turbine dentaire Apple Dent, disponible avec ou sans LED, haute vitesse, stérilisable autoclave.', en: 'Apple Dent dental turbine, available with or without LED, high speed, autoclave sterilizable.' }, featured: false, inStock: true },
  { name: { fr: 'Turbine COXO', en: 'COXO Turbine' }, brand: 'COXO', category: 'petit-equipement', price: 2200, images: [], description: { fr: 'Turbine dentaire COXO avec ou sans LED, couple élevé, tête mini, stérilisable 135°C.', en: 'COXO dental turbine with or without LED, high torque, mini head, sterilizable at 135°C.' }, featured: false, inStock: true },
  { name: { fr: 'Turbine Skyma Classe B', en: 'Skyma Class B Turbine' }, brand: 'Skyma', category: 'petit-equipement', price: 280, images: [], description: { fr: 'Turbine Skyma Classe B, haute vitesse économique, compatible 4 trous, stérilisable autoclave.', en: 'Skyma Class B turbine, economical high speed, 4-hole compatible, autoclave sterilizable.' }, featured: false, inStock: true },
  { name: { fr: 'Kit Rotatif 3pcs Skyma', en: 'Skyma 3-Piece Rotary Kit' }, brand: 'Skyma', category: 'petit-equipement', price: 750, images: [], description: { fr: 'Kit rotatif Skyma 3 pièces : turbine + contre-angle + bague, classe A ou B, solution complète économique.', en: 'Skyma 3-piece rotary kit: turbine + contra-angle + coupling, class A or B, complete economical solution.' }, featured: false, inStock: true },
  { name: { fr: 'Contre Angle Skyma Classe A', en: 'Skyma Class A Contra-Angle' }, brand: 'Skyma', category: 'petit-equipement', price: 220, images: [], description: { fr: 'Contre-angle Skyma Classe A, couple élevé, rotation 1:1, stérilisable autoclave, prise bur ISO standard.', en: 'Skyma Class A contra-angle, high torque, 1:1 rotation, autoclave sterilizable, standard ISO bur chuck.' }, featured: false, inStock: true },
  { name: { fr: 'Contre Angle Skyma Classe B', en: 'Skyma Class B Contra-Angle' }, brand: 'Skyma', category: 'petit-equipement', price: 180, images: [], description: { fr: 'Contre-angle Skyma Classe B, économique, rotation 1:1, compatible toutes turbines 4 trous standard.', en: 'Skyma Class B contra-angle, economical, 1:1 rotation, compatible with all standard 4-hole turbines.' }, featured: false, inStock: true },
  { name: { fr: 'Aéropolisseur NSK', en: 'NSK Air Polisher' }, brand: 'NSK', category: 'petit-equipement', price: 4500, images: [], description: { fr: 'Aéropolisseur NSK Prophy-Mate Neo, jet de poudre bicarbonate, polissage prophylactique supragingival.', en: 'NSK Prophy-Mate Neo air polisher, bicarbonate powder jet, supragingival prophylactic polishing.' }, featured: false, inStock: true },
  { name: { fr: 'Aéropolisseur Woodpecker', en: 'Woodpecker Air Polisher' }, brand: 'Woodpecker', category: 'petit-equipement', price: 2800, images: [], description: { fr: 'Aéropolisseur Woodpecker, prophylaxie dentaire par jet de poudre, embout orientable 360°.', en: 'Woodpecker air polisher, dental prophylaxis by powder jet, 360° orientable nozzle.' }, featured: false, inStock: true },
]

async function addMissing() {
  try {
    await mongoose.connect(process.env.MONGODB_URI)
    console.log('MongoDB connecté')

    let added = 0
    let skipped = 0

    for (const p of newProducts) {
      const exists = await Product.findOne({ 'name.fr': p.name.fr })
      if (exists) {
        console.log(`  ↷ déjà présent : ${p.name.fr}`)
        skipped++
      } else {
        await Product.create(p)
        console.log(`  ✓ ajouté : ${p.name.fr}`)
        added++
      }
    }

    console.log(`\nTerminé — ${added} produits ajoutés, ${skipped} ignorés (déjà existants)`)
    process.exit(0)
  } catch (err) {
    console.error('Erreur:', err)
    process.exit(1)
  }
}

addMissing()
