require('dotenv').config()
const mongoose = require('mongoose')
const Product = require('./models/Product')

const products = [
  // ── USAGE UNIQUE ──────────────────────────────────────────────
  { name: { fr: 'Gant Latex Oktan', en: 'Oktan Latex Glove' }, brand: 'Oktan', category: 'usage-unique', price: 480, images: ['/products/product-1.jpg'], description: { fr: 'Gants en latex de qualité professionnelle, disponibles en plusieurs tailles.', en: 'Professional quality latex gloves, available in multiple sizes.' }, featured: true, inStock: true },
  { name: { fr: 'Gant Nitril', en: 'Nitrile Glove' }, brand: 'Oktan', category: 'usage-unique', price: 480, images: ['/products/product-2.jpg'], description: { fr: 'Gants en nitrile sans latex, résistants aux produits chimiques.', en: 'Latex-free nitrile gloves, chemical resistant.' }, featured: false, inStock: true },
  { name: { fr: 'Masque en Couleur', en: 'Colored Mask' }, brand: 'AT Dental', category: 'usage-unique', price: 40, images: ['/products/product-3.jpg'], description: { fr: 'Masques chirurgicaux 3 plis, disponibles en plusieurs couleurs.', en: '3-ply surgical masks, available in multiple colors.' }, featured: false, inStock: true },
  { name: { fr: 'Casaque Jetable', en: 'Disposable Gown' }, brand: 'AT Dental', category: 'usage-unique', price: 70, images: ['/products/product-4.jpg'], description: { fr: 'Casaque jetable de protection, imperméable et légère.', en: 'Disposable protective gown, waterproof and lightweight.' }, featured: false, inStock: true },
  { name: { fr: 'Seringue Irrigation', en: 'Irrigation Syringe' }, brand: 'AT Dental', category: 'usage-unique', price: 65, images: ['/products/product-5.jpg'], description: { fr: "Seringue d'irrigation pour usage dentaire, embout courbe.", en: 'Dental irrigation syringe with curved tip.' }, featured: false, inStock: true },
  { name: { fr: 'Cotton Salivaire', en: 'Salivary Cotton Rolls' }, brand: 'AT Dental', category: 'usage-unique', price: 45, images: ['/products/product-6.jpg'], description: { fr: 'Rouleaux de coton salivaire absorbants stériles.', en: 'Sterile absorbent salivary cotton rolls.' }, featured: false, inStock: true },
  { name: { fr: 'Aiguille Dentaire Oktan', en: 'Oktan Dental Needle' }, brand: 'Oktan', category: 'usage-unique', price: 45, images: ['/products/product-7.jpg'], description: { fr: 'Aiguilles dentaires stériles usage unique, disponibles en plusieurs calibres.', en: 'Sterile single-use dental needles, available in multiple gauges.' }, featured: false, inStock: true },
  { name: { fr: 'Champ Stérile Standard', en: 'Standard Sterile Drape' }, brand: 'AT Dental', category: 'usage-unique', price: 250, images: ['/products/product-8.jpg'], description: { fr: "Champ stérile 75x90cm pour isolation du champ opératoire.", en: '75x90cm sterile drape for operative field isolation.' }, featured: false, inStock: true },

  // ── HYGIÈNE & DÉSINFECTION ────────────────────────────────────
  { name: { fr: 'Prosept Fortis', en: 'Prosept Fortis' }, brand: 'Procter', category: 'hygiene', price: 220, images: ['/products/product-9.jpg'], description: { fr: 'Désinfectant concentré pour instruments et surfaces dentaires.', en: 'Concentrated disinfectant for dental instruments and surfaces.' }, featured: true, inStock: true },
  { name: { fr: 'Prosept Spray', en: 'Prosept Spray' }, brand: 'Procter', category: 'hygiene', price: 140, images: ['/products/product-10.jpg'], description: { fr: "Spray désinfectant prêt à l'emploi pour surfaces et empreintes.", en: 'Ready-to-use disinfectant spray for surfaces and impressions.' }, featured: false, inStock: true },
  { name: { fr: 'Dento Viractis 77', en: 'Dento Viractis 77' }, brand: 'Viractis', category: 'hygiene', price: 580, images: ['/products/product-11.jpg'], description: { fr: 'Désinfectant de haut niveau pour instruments dentaires.', en: 'High-level disinfectant for dental instruments.' }, featured: false, inStock: true },
  { name: { fr: 'Lingettes DCC', en: 'DCC Wipes' }, brand: 'DCC', category: 'hygiene', price: 60, images: ['/products/product-12.jpg'], description: { fr: 'Lingettes désinfectantes pour surfaces, usage rapide.', en: 'Disinfecting surface wipes, quick use.' }, featured: false, inStock: true },
  { name: { fr: 'Panaspray NSK', en: 'Panaspray NSK' }, brand: 'NSK', category: 'hygiene', price: 350, images: ['/products/product-13.jpg'], description: { fr: 'Spray lubrifiant et désinfectant pour pièces à main NSK.', en: 'Lubricating and disinfecting spray for NSK handpieces.' }, featured: false, inStock: true },
  { name: { fr: 'Pack Stérilisation', en: 'Sterilization Pack' }, brand: 'AT Dental', category: 'hygiene', price: 19500, images: ['/products/product-14.jpg'], description: { fr: 'Pack complet : autoclave + soudeuse + distilateur. Solution clé en main.', en: 'Complete pack: autoclave + sealer + distiller. Turn-key solution.' }, featured: true, inStock: true },
  { name: { fr: 'Rouleaux Stérilisation N°7.5', en: 'Sterilization Rolls N°7.5' }, brand: 'AT Dental', category: 'hygiene', price: 220, images: ['/products/product-15.jpg'], description: { fr: 'Rouleaux de stérilisation thermosoudés, norme EN868.', en: 'Heat-sealed sterilization rolls, EN868 standard.' }, featured: false, inStock: true },

  // ── EMPREINTE ─────────────────────────────────────────────────
  { name: { fr: 'Alginate Cavex', en: 'Cavex Alginate' }, brand: 'Cavex', category: 'empreinte', price: 300, images: ['/products/product-16.png'], description: { fr: 'Alginate de précision à prise rapide, changement de couleur.', en: 'Fast-set precision alginate with color change.' }, featured: true, inStock: true },
  { name: { fr: 'Alginate Lascod', en: 'Lascod Alginate' }, brand: 'Lascod', category: 'empreinte', price: 60, images: ['/products/product-17.jpg'], description: { fr: 'Alginate irréversible haute précision, conditionnement économique.', en: 'High-precision irreversible alginate, economical packaging.' }, featured: false, inStock: true },
  { name: { fr: 'Alginate Zhermarck', en: 'Zhermarck Alginate' }, brand: 'Zhermarck', category: 'empreinte', price: 75, images: ['/products/product-18.jpg'], description: { fr: 'Alginate professionnel à consistance régulière et prise contrôlée.', en: 'Professional alginate with regular consistency and controlled set.' }, featured: false, inStock: true },
  { name: { fr: 'Bonasil A+ Putty & Light', en: 'Bonasil A+ Putty & Light' }, brand: 'Bonasil', category: 'empreinte', price: 400, images: ['/products/product-19.jpg'], description: { fr: "Silicone d'addition bicomposant, haute précision dimensionnelle.", en: 'Two-component addition silicone, high dimensional precision.' }, featured: false, inStock: true },
  { name: { fr: 'Kit Zeta Plus', en: 'Zeta Plus Kit' }, brand: 'Zhermack', category: 'empreinte', price: 175, images: ['/products/product-20.jpg'], description: { fr: "Kit d'empreinte complet avec putty et wash, idéal pour prothèses.", en: 'Complete impression kit with putty and wash, ideal for prosthetics.' }, featured: false, inStock: true },
  { name: { fr: 'Viscostat', en: 'Viscostat' }, brand: 'Ultradent', category: 'empreinte', price: 500, images: ['/products/product-21.jpg'], description: { fr: 'Gel hémostatique à 25% sulfate ferrique pour contrôle du saignement.', en: '25% ferric sulfate hemostatic gel for bleeding control.' }, featured: false, inStock: true },
  { name: { fr: 'Ultrapack', en: 'Ultrapack' }, brand: 'Ultradent', category: 'empreinte', price: 170, images: ['/products/product-22.jpg'], description: { fr: "Fil de rétraction gingivale imprégné ou non pour prise d'empreinte précise.", en: 'Impregnated or plain gingival retraction cord for precise impressions.' }, featured: false, inStock: true },

  // ── BLANCHIMENT ───────────────────────────────────────────────
  { name: { fr: 'Opalescence PF', en: 'Opalescence PF' }, brand: 'Ultradent', category: 'blanchiment', price: 600, images: ['/products/product-23.jpg'], description: { fr: 'Gel de blanchiment ambulatoire au peroxyde de carbamide, avec fluor.', en: 'Take-home whitening gel with carbamide peroxide and fluoride.' }, featured: true, inStock: true },
  { name: { fr: 'Opalescence Boost 40%', en: 'Opalescence Boost 40%' }, brand: 'Ultradent', category: 'blanchiment', price: 800, images: ['/products/product-24.jpg'], description: { fr: 'Blanchiment en cabinet activé chimiquement, résultats immédiats.', en: 'In-office chemically activated whitening, immediate results.' }, featured: true, inStock: true },
  { name: { fr: 'Zoom 2 Patients', en: 'Zoom 2 Patients' }, brand: 'Philips', category: 'blanchiment', price: 2050, images: ['/products/product-25.jpg'], description: { fr: 'Kit Zoom 2 pour blanchiment en cabinet, 2 patients.', en: 'Zoom 2 in-office whitening kit for 2 patients.' }, featured: false, inStock: true },
  { name: { fr: 'Opalescence Endo', en: 'Opalescence Endo' }, brand: 'Ultradent', category: 'blanchiment', price: 720, images: ['/products/product-26.jpg'], description: { fr: 'Gel de blanchiment interne pour dents dépulpées.', en: 'Internal bleaching gel for non-vital teeth.' }, featured: false, inStock: true },
  { name: { fr: 'Icon', en: 'Icon' }, brand: 'DMG', category: 'blanchiment', price: 1050, images: ['/products/product-27.jpg'], description: { fr: 'Traitement par infiltration des taches blanches et lésions débutantes.', en: 'Infiltration treatment for white spots and initial lesions.' }, featured: false, inStock: true },
  { name: { fr: 'Top Dam', en: 'Top Dam' }, brand: 'FGM', category: 'blanchiment', price: 220, images: ['/products/product-28.jpg'], description: { fr: 'Digue liquide photodurcissable pour protection gingivale lors du blanchiment.', en: 'Light-cured liquid dam for gingival protection during whitening.' }, featured: false, inStock: true },
  { name: { fr: 'Lampe Blanchiment Flash', en: 'Flash Whitening Lamp' }, brand: 'Flash', category: 'blanchiment', price: 17000, images: ['/products/product-29.jpg'], description: { fr: 'Lampe de blanchiment professionnel haute puissance pour usage cabinet.', en: 'High-power professional whitening lamp for in-office use.' }, featured: false, inStock: true },

  // ── ENDODONTIE ────────────────────────────────────────────────
  { name: { fr: 'Biodentine', en: 'Biodentine' }, brand: 'Septodont', category: 'endodontie', price: 1000, images: ['/products/product-30.jpg'], description: { fr: 'Substitut dentinaire bioactif à base de silicate tricalcique.', en: 'Bioactive dentin substitute based on tricalcium silicate.' }, featured: true, inStock: true },
  { name: { fr: 'MTA Bioseal', en: 'MTA Bioseal' }, brand: 'Bioseal', category: 'endodontie', price: 730, images: ['/products/product-31.jpg'], description: { fr: 'Ciment MTA pour obturation et réparation des perforations radiculaires.', en: 'MTA cement for root canal obturation and perforation repair.' }, featured: false, inStock: true },
  { name: { fr: 'Adseal', en: 'Adseal' }, brand: 'Meta', category: 'endodontie', price: 270, images: ['/products/product-32.jpg'], description: { fr: 'Ciment de scellement canalaire à base de résine époxy.', en: 'Epoxy resin-based root canal sealer.' }, featured: false, inStock: true },
  { name: { fr: 'Ceraseal', en: 'Ceraseal' }, brand: 'Meta', category: 'endodontie', price: 950, images: ['/products/product-33.jpg'], description: { fr: 'Ciment endodontique biocéramique, résorbable et biocompatible.', en: 'Bioceramic endodontic cement, resorbable and biocompatible.' }, featured: false, inStock: true },
  { name: { fr: 'BioRoot Flow', en: 'BioRoot Flow' }, brand: 'Septodont', category: 'endodontie', price: 950, images: ['/products/product-34.jpg'], description: { fr: 'Ciment de scellement biocéramique injectable, excellente biocompatibilité.', en: 'Injectable bioceramic sealer, excellent biocompatibility.' }, featured: false, inStock: true },
  { name: { fr: 'Ultracal XS', en: 'Ultracal XS' }, brand: 'Ultradent', category: 'endodontie', price: 524, images: ['/products/product-35.jpg'], description: { fr: 'Hydroxyde de calcium injectable pour médication inter-séances.', en: 'Injectable calcium hydroxide for inter-appointment medication.' }, featured: false, inStock: true },
  { name: { fr: 'Gutta Percha Point Paper', en: 'Gutta Percha Point Paper' }, brand: 'Dentsply', category: 'endodontie', price: 55, images: ['/products/product-36.jpg'], description: { fr: "Cônes de gutta-percha ISO et points papier absorbants.", en: 'ISO gutta-percha cones and absorbent paper points.' }, featured: false, inStock: true },

  // ── CIMENT ────────────────────────────────────────────────────
  { name: { fr: 'Fuji I', en: 'Fuji I' }, brand: 'GC', category: 'ciment', price: 650, images: ['/products/product-37.jpg'], description: { fr: 'Ciment verre ionomère de scellement type I, haute rétention.', en: 'Type I glass ionomer luting cement, high retention.' }, featured: false, inStock: true },
  { name: { fr: 'Fuji IX', en: 'Fuji IX' }, brand: 'GC', category: 'ciment', price: 650, images: ['/products/product-38.jpg'], description: { fr: 'CVI haute viscosité pour restaurations et obturations postérieures.', en: 'High-viscosity GIC for posterior restorations and obturations.' }, featured: true, inStock: true },
  { name: { fr: 'Fuji Plus', en: 'Fuji Plus' }, brand: 'GC', category: 'ciment', price: 550, images: ['/products/product-39.jpg'], description: { fr: 'Ciment verre ionomère modifié par résine pour scellement de prothèses.', en: 'Resin-modified glass ionomer cement for prosthetic cementation.' }, featured: false, inStock: true },
  { name: { fr: 'Ketac Cem', en: 'Ketac Cem' }, brand: '3M', category: 'ciment', price: 550, images: ['/products/product-40.jpg'], description: { fr: 'Ciment verre ionomère 3M pour scellement couronnes et bridges.', en: '3M glass ionomer cement for crown and bridge cementation.' }, featured: false, inStock: true },
  { name: { fr: 'Equia Forte HT', en: 'Equia Forte HT' }, brand: 'GC', category: 'ciment', price: 2795, images: ['/products/product-41.jpg'], description: { fr: 'Système CVI haute performance pour restaurations postérieures de classe II.', en: 'High-performance GIC system for class II posterior restorations.' }, featured: false, inStock: true },
  { name: { fr: 'Provicol', en: 'Provicol' }, brand: 'VOCO', category: 'ciment', price: 330, images: ['/products/product-42.jpg'], description: { fr: "Ciment provisoire à l'hydroxyde de zinc, scellement temporaire.", en: 'Zinc hydroxide temporary cement, temporary cementation.' }, featured: false, inStock: true },
  { name: { fr: 'G-Cem Veneer', en: 'G-Cem Veneer' }, brand: 'GC', category: 'ciment', price: 2700, images: ['/products/product-43.jpg'], description: { fr: 'Ciment résine dual-cure pour collage de facettes et inlays esthétiques.', en: 'Dual-cure resin cement for bonding veneers and esthetic inlays.' }, featured: false, inStock: true },

  // ── RESTAURATION ──────────────────────────────────────────────
  { name: { fr: 'Gradia Direct', en: 'Gradia Direct' }, brand: 'GC', category: 'restauration', price: 280, images: ['/products/product-44.jpg'], description: { fr: 'Composite microhybride universel pour restaurations antérieures et postérieures.', en: 'Universal microhybrid composite for anterior and posterior restorations.' }, featured: true, inStock: true },
  { name: { fr: 'Z 250', en: 'Z 250' }, brand: '3M', category: 'restauration', price: 320, images: ['/products/product-45.jpg'], description: { fr: 'Composite universel 3M ESPE, haute résistance et esthétique.', en: '3M ESPE universal composite, high strength and esthetics.' }, featured: false, inStock: true },
  { name: { fr: 'Tetric N-Ceram', en: 'Tetric N-Ceram' }, brand: 'Ivoclar', category: 'restauration', price: 180, images: ['/products/product-46.jpg'], description: { fr: 'Composite nano-hybride universel pour restaurations directes.', en: 'Universal nano-hybrid composite for direct restorations.' }, featured: false, inStock: true },
  { name: { fr: 'G-Aenial Universal Flo', en: 'G-Aenial Universal Flo' }, brand: 'GC', category: 'restauration', price: 640, images: ['/products/product-47.jpg'], description: { fr: 'Composite fluide universel haute esthétique, compatible tous adhésifs.', en: 'Universal flowable composite, high esthetics, compatible with all adhesives.' }, featured: false, inStock: true },
  { name: { fr: 'Essentia Kit', en: 'Essentia Kit' }, brand: 'GC', category: 'restauration', price: 2850, images: ['/products/product-48.jpg'], description: { fr: 'Kit composite stratification esthétique avancée, teintes naturelles.', en: 'Advanced esthetic layering composite kit, natural shades.' }, featured: false, inStock: true },
  { name: { fr: 'Reflectys Flow', en: 'Reflectys Flow' }, brand: 'Itena', category: 'restauration', price: 180, images: ['/products/product-49.jpg'], description: { fr: 'Composite fluide universel, excellente fluidité et adaptation marginale.', en: 'Universal flowable composite, excellent flow and marginal adaptation.' }, featured: false, inStock: true },

  // ── RECONSTITUTION ────────────────────────────────────────────
  { name: { fr: 'Adhésif Universal 3M', en: '3M Universal Adhesive' }, brand: '3M', category: 'reconstitution', price: 680, images: ['/products/product-50.jpg'], description: { fr: 'Adhésif universel Scotchbond, compatible mordançage total et automordançant.', en: 'Scotchbond universal adhesive, total-etch and self-etch compatible.' }, featured: true, inStock: true },
  { name: { fr: 'Protemp 3M', en: '3M Protemp' }, brand: '3M', category: 'reconstitution', price: 1100, images: ['/products/product-51.jpg'], description: { fr: 'Composite bis-acryl pour prothèses provisoires de haute esthétique.', en: 'Bis-acryl composite for high esthetic provisional prosthetics.' }, featured: false, inStock: true },
  { name: { fr: 'Dentocrown', en: 'Dentocrown' }, brand: 'Dentocrown', category: 'reconstitution', price: 650, images: ['/products/product-52.jpg'], description: { fr: 'Système de reconstitution corono-radiculaire par technique directe.', en: 'Corono-radicular reconstruction system using direct technique.' }, featured: false, inStock: true },
  { name: { fr: 'Dentoclic Fibre de Verre', en: 'Dentoclic Fiberglass Post' }, brand: 'Itena', category: 'reconstitution', price: 160, images: ['/products/product-53.jpg'], description: { fr: 'Tenons en fibre de verre pré-imprégnés, haute résistance à la flexion.', en: 'Pre-impregnated fiberglass posts, high flexural strength.' }, featured: false, inStock: true },
  { name: { fr: 'Acide Spident', en: 'Spident Acid' }, brand: 'Spident', category: 'reconstitution', price: 150, images: ['/products/product-54.jpg'], description: { fr: "Gel d'acide phosphorique 37% pour mordançage de l'émail et dentine.", en: '37% phosphoric acid gel for etching enamel and dentin.' }, featured: false, inStock: true },

  // ── FINITION & FRAISE ─────────────────────────────────────────
  { name: { fr: 'Fraise Jota', en: 'Jota Bur' }, brand: 'Jota', category: 'fraise', price: 160, images: ['/products/product-55.jpg'], description: { fr: 'Fraises dentaires suisses Jota, haute précision, longue durabilité.', en: 'Swiss Jota dental burs, high precision, long durability.' }, featured: true, inStock: true },
  { name: { fr: 'Fraise Mani', en: 'Mani Bur' }, brand: 'Mani', category: 'fraise', price: 70, images: ['/products/product-56.jpg'], description: { fr: 'Fraises carbure de tungstène Mani, coupe précise et économique.', en: 'Mani tungsten carbide burs, precise cut and economical.' }, featured: false, inStock: true },
  { name: { fr: 'Diamond Polish', en: 'Diamond Polish' }, brand: 'AT Dental', category: 'fraise', price: 414, images: ['/products/product-57.jpg'], description: { fr: 'Pâte de polissage diamantée pour finition composite.', en: 'Diamond polishing paste for composite finishing.' }, featured: false, inStock: true },
  { name: { fr: 'Disque Soflex 3M', en: '3M Sof-Lex Disc' }, brand: '3M', category: 'fraise', price: 260, images: ['/products/product-58.jpg'], description: { fr: "Disques de polissage Sof-Lex 3M, grain variable pour finition optimale.", en: '3M Sof-Lex polishing discs, variable grit for optimal finishing.' }, featured: false, inStock: true },
  { name: { fr: 'Perfect Polish Itena', en: 'Itena Perfect Polish' }, brand: 'Itena', category: 'fraise', price: 446, images: ['/products/product-59.jpg'], description: { fr: 'Kit de polissage composite complet, 4 étapes de finition.', en: 'Complete composite polishing kit, 4 finishing steps.' }, featured: false, inStock: true },
  { name: { fr: 'Detartrine Z', en: 'Detartrine Z' }, brand: 'Septodont', category: 'fraise', price: 400, images: ['/products/product-60.jpg'], description: { fr: 'Pâte prophylactique Détartrine Z pour élimination du tartre souple.', en: 'Detartrine Z prophylactic paste for soft tartar removal.' }, featured: false, inStock: true },

  // ── INSTRUMENTATION ───────────────────────────────────────────
  { name: { fr: 'Série Daviers 10 pcs', en: 'Forceps Set 10 pcs' }, brand: 'Falcon', category: 'instrumentation', price: 1550, images: ['/products/product-61.jpg'], description: { fr: "Set de 10 daviers d'extraction acier inoxydable, autoclavables.", en: 'Set of 10 stainless steel extraction forceps, autoclavable.' }, featured: true, inStock: true },
  { name: { fr: 'Kit Digue', en: 'Rubber Dam Kit' }, brand: 'Falcon', category: 'instrumentation', price: 1650, images: ['/products/product-62.jpg'], description: { fr: 'Kit complet pour pose de digue dentaire, matériaux inclus.', en: 'Complete rubber dam placement kit, materials included.' }, featured: false, inStock: true },
  { name: { fr: 'Seringue Anesthésie', en: 'Anesthesia Syringe' }, brand: 'Falcon', category: 'instrumentation', price: 180, images: ['/products/product-63.jpg'], description: { fr: 'Seringue carpule aspirante inox, ergonomique et autoclavable.', en: 'Stainless steel aspirating carpule syringe, ergonomic and autoclavable.' }, featured: false, inStock: true },
  { name: { fr: 'Miroir à Bouche', en: 'Mouth Mirror' }, brand: 'Falcon', category: 'instrumentation', price: 160, images: ['/products/product-64.jpg'], description: { fr: 'Miroirs dentaires double face, manche octogonal antidérapant.', en: 'Double-sided dental mirrors, non-slip octagonal handle.' }, featured: false, inStock: true },
  { name: { fr: 'Précelles Chirurgicales', en: 'Surgical Tweezers' }, brand: 'Falcon', category: 'instrumentation', price: 45, images: ['/products/product-65.jpg'], description: { fr: 'Pinces chirurgicales fines pour manipulation de tissus délicats.', en: 'Fine surgical tweezers for delicate tissue manipulation.' }, featured: false, inStock: true },
  { name: { fr: 'Arrache Couronne', en: 'Crown Remover' }, brand: 'Falcon', category: 'instrumentation', price: 380, images: ['/products/product-66.jpg'], description: { fr: 'Instrument pour dépose de couronnes provisoires et définitives.', en: 'Instrument for removing provisional and definitive crowns.' }, featured: false, inStock: true },

  // ── PETIT ÉQUIPEMENT ──────────────────────────────────────────
  { name: { fr: 'Turbine Pana Air NSK', en: 'NSK Pana Air Turbine' }, brand: 'NSK', category: 'petit-equipement', price: 1950, images: ['/products/product-67.jpg'], description: { fr: 'Turbine dentaire NSK Pana-Air, ultra-légère, haute vitesse, 4 trous.', en: 'NSK Pana-Air dental turbine, ultra-light, high speed, 4-hole.' }, featured: true, inStock: true },
  { name: { fr: 'Dyna LED NSK', en: 'NSK Dyna LED' }, brand: 'NSK', category: 'petit-equipement', price: 3600, images: ['/products/product-68.jpg'], description: { fr: 'Contre-angle LED haute performance NSK Dyna, couple élevé.', en: 'NSK Dyna high-performance LED contra-angle, high torque.' }, featured: false, inStock: true },
  { name: { fr: 'Détartreur Woodpecker UDS', en: 'Woodpecker UDS Scaler' }, brand: 'Woodpecker', category: 'petit-equipement', price: 2900, images: ['/products/product-69.jpg'], description: { fr: 'Détartreur ultrasonique Woodpecker UDS, puissant et silencieux.', en: 'Woodpecker UDS ultrasonic scaler, powerful and quiet.' }, featured: false, inStock: true },
  { name: { fr: 'Détartreur D8 DTE', en: 'DTE D8 Scaler' }, brand: 'DTE', category: 'petit-equipement', price: 2800, images: ['/products/product-70.jpg'], description: { fr: 'Détartreur piézoélectrique DTE D8, 5 inserts inclus.', en: 'DTE D8 piezoelectric scaler, 5 inserts included.' }, featured: false, inStock: true },
  { name: { fr: 'Lampe O-Star', en: 'O-Star Lamp' }, brand: 'O-Star', category: 'petit-equipement', price: 9000, images: ['/products/product-71.jpg'], description: { fr: 'Lampe de photopolymérisation LED haute intensité, minuterie intégrée.', en: 'High-intensity LED curing light with built-in timer.' }, featured: false, inStock: true },
  { name: { fr: 'I LED II', en: 'I LED II' }, brand: 'Woodpecker', category: 'petit-equipement', price: 1500, images: ['/products/product-72.jpg'], description: { fr: 'Lampe LED de photopolymérisation sans fil, légère et ergonomique.', en: 'Wireless LED curing light, lightweight and ergonomic.' }, featured: false, inStock: true },
  { name: { fr: 'Moteur Endo DTE', en: 'DTE Endo Motor' }, brand: 'DTE', category: 'petit-equipement', price: 7000, images: ['/products/product-73.jpg'], description: { fr: "Moteur endodontique électronique avec localisateur d'apex intégré.", en: 'Electronic endodontic motor with integrated apex locator.' }, featured: false, inStock: true },
  { name: { fr: 'Turbine Skyma Classe A', en: 'Skyma Class A Turbine' }, brand: 'Skyma', category: 'petit-equipement', price: 330, images: ['/products/product-74.jpg'], description: { fr: 'Turbine classe A certifiée, haute vitesse, stérilisable autoclave.', en: 'Class A certified turbine, high speed, autoclave sterilizable.' }, featured: false, inStock: true },

  // ── GRAND ÉQUIPEMENT ──────────────────────────────────────────
  { name: { fr: 'RVG Vatech', en: 'Vatech RVG' }, brand: 'Vatech', category: 'grand-equipement', price: 24000, images: ['/products/product-75.jpg'], description: { fr: 'Capteur radiographique numérique Vatech, haute résolution et faible irradiation.', en: 'Vatech digital radiographic sensor, high resolution and low radiation.' }, featured: true, inStock: true },
  { name: { fr: 'Radio Portable Vatech', en: 'Vatech Portable X-Ray' }, brand: 'Vatech', category: 'grand-equipement', price: 28000, images: ['/products/product-76.jpg'], description: { fr: 'Appareil radiographique portable Vatech, léger et maniable.', en: 'Vatech portable X-ray unit, lightweight and easy to handle.' }, featured: false, inStock: true },
  { name: { fr: 'Radio Mural Vatech', en: 'Vatech Wall X-Ray' }, brand: 'Vatech', category: 'grand-equipement', price: 26600, images: ['/products/product-77.jpg'], description: { fr: 'Générateur de rayons X mural Vatech, bras articulé longue portée.', en: 'Vatech wall-mounted X-ray generator, long-reach articulated arm.' }, featured: false, inStock: true },
  { name: { fr: 'Aspiration 4TEK', en: '4TEK Suction Unit' }, brand: '4TEK', category: 'grand-equipement', price: 8700, images: ['/products/product-78.jpg'], description: { fr: "Groupe d'aspiration chirurgicale 4TEK, puissant et silencieux.", en: '4TEK surgical suction unit, powerful and quiet.' }, featured: false, inStock: true },
  { name: { fr: 'Compresseur Runyes', en: 'Runyes Compressor' }, brand: 'Runyes', category: 'grand-equipement', price: 3500, images: ['/products/product-79.jpg'], description: { fr: 'Compresseur dentaire sans huile Runyes, silencieux et compact.', en: 'Runyes oil-free dental compressor, silent and compact.' }, featured: false, inStock: true },
  { name: { fr: 'Moteur Implant NSK', en: 'NSK Implant Motor' }, brand: 'NSK', category: 'grand-equipement', price: 29000, images: ['/products/product-80.jpg'], description: { fr: "Moteur d'implantologie NSK, couple élevé, programmes préréglés.", en: 'NSK implantology motor, high torque, preset programs.' }, featured: false, inStock: true },
  { name: { fr: 'Radio Mobile Runyes', en: 'Runyes Mobile X-Ray' }, brand: 'Runyes', category: 'grand-equipement', price: 16000, images: ['/products/product-81.webp'], description: { fr: 'Générateur de rayons X mobile Runyes, rotation 360° et réglage facile.', en: 'Runyes mobile X-ray generator, 360° rotation and easy adjustment.' }, featured: false, inStock: true },

  // ── FAUTEUILS DENTAIRES ───────────────────────────────────────
  { name: { fr: 'Fauteuil Runyes', en: 'Runyes Dental Chair' }, brand: 'Runyes', category: 'fauteuils', price: 38500, images: ['/products/product-82.jpg'], description: { fr: 'Fauteuil dentaire Runyes, confort optimal, structure robuste, finitions soignées.', en: 'Runyes dental chair, optimal comfort, robust structure, quality finishes.' }, featured: true, inStock: true },
  { name: { fr: 'Fauteuil Stern Weber', en: 'Stern Weber Dental Chair' }, brand: 'Stern Weber', category: 'fauteuils', price: 72000, images: ['/products/product-83.jpg'], description: { fr: 'Fauteuil Stern Weber S200, design ergonomique, confort patient et praticien.', en: 'Stern Weber S200 chair, ergonomic design, patient and practitioner comfort.' }, featured: false, inStock: true },
  { name: { fr: 'Fauteuil Join Champ ZC-5400', en: 'Join Champ ZC-5400 Chair' }, brand: 'Join Champ', category: 'fauteuils', price: 45000, images: ['/products/product-84.webp'], description: { fr: 'Fauteuil Join Champ ZC-5400, conception moderne, matériaux de qualité.', en: 'Join Champ ZC-5400 chair, modern design, quality materials.' }, featured: false, inStock: true },
  { name: { fr: 'Fauteuil Castellini', en: 'Castellini Dental Chair' }, brand: 'Castellini', category: 'fauteuils', price: 98000, images: ['/products/product-85.jpg'], description: { fr: "Unité dentaire Castellini haut de gamme, équipement complet intégré.", en: 'High-end Castellini dental unit, complete integrated equipment.' }, featured: false, inStock: true },

  // ── TECHNOLOGIE ───────────────────────────────────────────────
  { name: { fr: 'Scanner Intra-Oral 3DS V3 Pro', en: '3DS V3 Pro Intraoral Scanner' }, brand: 'Runyes', category: 'technologie', price: 75000, images: ['/products/product-86.jpg'], description: { fr: 'Scanner intra-oral Runyes 3DS V3 Pro, AI Scan, câble détachable et fixe.', en: 'Runyes 3DS V3 Pro intraoral scanner, AI Scan, detachable and fixed cable.' }, featured: true, inStock: true },
  { name: { fr: 'Imprimante 3D HALOT-MAGE S 14K', en: 'HALOT-MAGE S 14K 3D Printer' }, brand: 'Creality', category: 'technologie', price: 7500, images: ['/products/product-87.jpg'], description: { fr: "Imprimante 3D résine Mono LCD 14K, vitesse 150mm/h, purificateur d'air intégré.", en: '14K Mono LCD resin 3D printer, 150mm/h speed, integrated air purifier.' }, featured: false, inStock: true },
  { name: { fr: 'Wash & Cure Machine', en: 'Wash & Cure Machine' }, brand: 'Creality', category: 'technologie', price: 2800, images: ['/products/product-88.jpg'], description: { fr: 'Machine de lavage et séchage UV pour impressions 3D dentaires.', en: 'Washing and UV curing machine for dental 3D prints.' }, featured: false, inStock: true },
]

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI)
    console.log('MongoDB connecté')

    await Product.deleteMany()
    console.log('Produits existants supprimés')

    const created = await Product.insertMany(products)
    console.log(`${created.length} produits insérés avec succès`)

    process.exit(0)
  } catch (err) {
    console.error('Erreur seed:', err)
    process.exit(1)
  }
}

seed()
