require('dotenv').config({ path: require('path').join(__dirname, '../.env') })
const mongoose = require('mongoose')
const Product = require('../models/Product')

const newProducts = [
  // ── EMPREINTE ─────────────────────────────────────────────────
  { name: { fr: 'Kit Durosil', en: 'Durosil Kit' }, brand: 'Zhermack', category: 'empreinte', price: 250, description: { fr: 'Kit de silicone à condensation Durosil, base et catalyseur, prise rapide et précise.', en: 'Durosil condensation silicone kit, base and catalyst, fast and precise setting.' } },
  { name: { fr: 'Kit Silaxil', en: 'Silaxil Kit' }, brand: 'Septodont', category: 'empreinte', price: 280, description: { fr: 'Silicone à condensation Silaxil en kit putty et light pour empreintes de qualité.', en: 'Silaxil condensation silicone kit in putty and light for quality impressions.' } },
  { name: { fr: 'Kit Dent Plus', en: 'Dent Plus Kit' }, brand: 'AT Dental', category: 'empreinte', price: 220, description: { fr: 'Kit d\'empreinte silicone complet Dent Plus, idéal pour prothèses fixes et amovibles.', en: 'Complete Dent Plus silicone impression kit, ideal for fixed and removable prosthetics.' } },
  { name: { fr: 'Express Putty et Light', en: 'Express Putty and Light' }, brand: '3M', category: 'empreinte', price: 450, description: { fr: 'Silicone d\'addition 3M Express, putty et wash, précision dimensionnelle exceptionnelle.', en: '3M Express addition silicone, putty and wash, exceptional dimensional accuracy.' } },
  { name: { fr: 'Élite HD Putty et Light', en: 'Elite HD Putty and Light' }, brand: 'Zhermack', category: 'empreinte', price: 420, description: { fr: 'Silicone d\'addition Élite HD Zhermack, haute définition de surface pour prothèses esthétiques.', en: 'Zhermack Elite HD addition silicone, high surface definition for aesthetic prosthetics.' } },
  { name: { fr: 'Panasil Putty et Light', en: 'Panasil Putty and Light' }, brand: 'Kettenbach', category: 'empreinte', price: 380, description: { fr: 'Silicone d\'addition Panasil Kettenbach, excellente stabilité dimensionnelle à long terme.', en: 'Kettenbach Panasil addition silicone, excellent long-term dimensional stability.' } },
  { name: { fr: 'Hydrorise Putty et Light', en: 'Hydrorise Putty and Light' }, brand: 'Zhermack', category: 'empreinte', price: 390, description: { fr: 'Silicone d\'addition hydrophile Hydrorise, reproduction fidèle des détails même en milieu humide.', en: 'Hydrorise hydrophilic addition silicone, faithful detail reproduction even in moist conditions.' } },
  { name: { fr: 'Hemostal Gel', en: 'Hemostal Gel' }, brand: 'Sans Marque', category: 'empreinte', price: 180, description: { fr: 'Gel hémostatique à l\'aluminium pour contrôle du saignement gingival avant empreinte.', en: 'Aluminum hemostatic gel for gingival bleeding control before impression.' } },
  { name: { fr: 'Traxodent', en: 'Traxodent' }, brand: 'Premier', category: 'empreinte', price: 320, description: { fr: 'Pâte de rétraction gingivale Traxodent, hémostatique, facilite la prise d\'empreinte sous-gingivale.', en: 'Traxodent gingival retraction paste, hemostatic, facilitates subgingival impression taking.' } },
  { name: { fr: 'Astringent 3M', en: '3M Astringent' }, brand: '3M', category: 'empreinte', price: 350, description: { fr: 'Solution astringente 3M au sulfate ferrique, contrôle rapide du saignement gingival.', en: '3M ferric sulfate astringent solution, rapid control of gingival bleeding.' } },
  { name: { fr: 'Porte Empreinte Métal/Plastique', en: 'Metal/Plastic Impression Tray' }, brand: 'AT Dental', category: 'empreinte', price: 90, description: { fr: 'Porte-empreinte universel disponible en métal autoclavable ou plastique usage unique, toutes tailles.', en: 'Universal impression tray available in autoclavable metal or single-use plastic, all sizes.' } },

  // ── BLANCHIMENT ───────────────────────────────────────────────
  { name: { fr: 'Flash 2 Patients', en: 'Flash 2 Patients' }, brand: 'Flash', category: 'blanchiment', price: 1800, description: { fr: 'Kit de blanchiment en cabinet Flash pour 2 patients, résultats visibles dès la première séance.', en: 'Flash in-office whitening kit for 2 patients, visible results from the first session.' } },
  { name: { fr: 'Power Whitening 2 Patients', en: 'Power Whitening 2 Patients' }, brand: 'FGM', category: 'blanchiment', price: 1500, description: { fr: 'Kit blanchiment professionnel FGM Power Whitening pour 2 patients, activation LED.', en: 'FGM Power Whitening professional kit for 2 patients, LED activation.' } },
  { name: { fr: 'Whitness HP Rouge', en: 'Whitness HP Red' }, brand: 'FGM', category: 'blanchiment', price: 1200, description: { fr: 'Gel de blanchiment Whitness HP 35% FGM, usage cabinet, flacon rouge, résultats rapides.', en: 'FGM Whitness HP 35% whitening gel, in-office use, red bottle, fast results.' } },
  { name: { fr: 'Opalustre', en: 'Opalustre' }, brand: 'Ultradent', category: 'blanchiment', price: 550, description: { fr: 'Pâte d\'élimination des fluoroses légères à modérées par microabrasion à l\'acide chlorhydrique.', en: 'Paste for removal of mild to moderate fluorosis by hydrochloric acid microabrasion.' } },
  { name: { fr: 'Opaldame', en: 'Opaldame' }, brand: 'Ultradent', category: 'blanchiment', price: 280, description: { fr: 'Digue de protection gingivale Opaldame, photopolymérisable, protection efficace lors du blanchiment.', en: 'Opaldame light-cured gingival barrier dam, effective protection during whitening.' } },
  { name: { fr: 'Opalescence Dentifrice', en: 'Opalescence Toothpaste' }, brand: 'Ultradent', category: 'blanchiment', price: 120, description: { fr: 'Dentifrice blanchissant Opalescence, formule fluorée, maintien des résultats de blanchiment.', en: 'Opalescence whitening toothpaste, fluoride formula, maintains whitening results.' } },
  { name: { fr: 'Home Whitening 22%/35%', en: 'Home Whitening 22%/35%' }, brand: 'Ultradent', category: 'blanchiment', price: 650, description: { fr: 'Gel de blanchiment ambulatoire peroxyde d\'hydrogène 22% ou 35%, en gouttière sur mesure.', en: 'Take-home whitening gel hydrogen peroxide 22% or 35%, in custom tray.' } },
  { name: { fr: 'Nite White 16%/22%', en: 'Nite White 16%/22%' }, brand: 'Philips', category: 'blanchiment', price: 680, description: { fr: 'Gel de blanchiment nocturne Nite White Philips, peroxyde de carbamide 16% ou 22%, application en gouttière.', en: 'Philips Nite White overnight whitening gel, carbamide peroxide 16% or 22%, tray application.' } },
  { name: { fr: 'Beyond', en: 'Beyond' }, brand: 'Beyond', category: 'blanchiment', price: 1400, description: { fr: 'Système de blanchiment professionnel Beyond avec gel activé par lampe LED, usage cabinet.', en: 'Beyond professional whitening system with LED lamp-activated gel, in-office use.' } },
  { name: { fr: 'Lampe Zoom avec 5 Coffrets Blanchiment', en: 'Zoom Lamp with 5 Whitening Kits' }, brand: 'Philips', category: 'blanchiment', price: 25000, description: { fr: 'Lampe Philips Zoom! avec 5 coffrets blanchiment inclus, système de référence pour blanchiment en cabinet.', en: 'Philips Zoom! lamp with 5 whitening kits included, reference system for in-office whitening.' } },
  { name: { fr: 'Lampe COXO', en: 'COXO Lamp' }, brand: 'COXO', category: 'blanchiment', price: 8000, description: { fr: 'Lampe de blanchiment dentaire COXO LED haute puissance, légère et maniable pour usage cabinet.', en: 'COXO LED high-power dental whitening lamp, lightweight and easy to handle for in-office use.' } },
  { name: { fr: 'Lampe de Blanchiment Wood', en: 'Wood Whitening Lamp' }, brand: 'Woodpecker', category: 'blanchiment', price: 6500, description: { fr: 'Lampe de blanchiment Woodpecker LED puissante, multi-longueurs d\'onde, résultats optimaux.', en: 'Powerful Woodpecker LED whitening lamp, multi-wavelength, optimal results.' } },
  { name: { fr: 'Lampe Blanchiment sans Support', en: 'Whitening Lamp without Stand' }, brand: 'Sans Marque', category: 'blanchiment', price: 4500, description: { fr: 'Lampe de blanchiment LED portable sans support, facilement repositionnable, idéale pour petits cabinets.', en: 'Portable LED whitening lamp without stand, easily repositionable, ideal for small offices.' } },

  // ── ENDODONTIE ────────────────────────────────────────────────
  { name: { fr: 'Revo S+', en: 'Revo S+' }, brand: 'Micro Mega', category: 'endodontie', price: 3200, description: { fr: 'Moteur endodontique Revo S+ Micro Mega, localisateur d\'apex intégré, programmes préréglés.', en: 'Revo S+ Micro Mega endodontic motor with integrated apex locator and preset programs.' } },
  { name: { fr: 'Orodeka', en: 'Orodeka' }, brand: 'Sans Marque', category: 'endodontie', price: 250, description: { fr: 'Solution chélatrice Orodeka pour irrigation et nettoyage canalaire, ramollissement de la dentine.', en: 'Orodeka chelating solution for canal irrigation and cleaning, dentin softening.' } },
  { name: { fr: 'Lime Fanta Gold', en: 'Fanta Gold File' }, brand: 'Fanta', category: 'endodontie', price: 180, description: { fr: 'Limes Fanta Gold en NiTi, flexibilité maximale, résistance à la fracture améliorée, mise en forme rapide.', en: 'Fanta Gold NiTi files, maximum flexibility, improved fracture resistance, fast shaping.' } },
  { name: { fr: 'Lime Fanta AF F One', en: 'Fanta AF F One File' }, brand: 'Fanta', category: 'endodontie', price: 180, description: { fr: 'Limes Fanta AF F One en NiTi traité thermiquement, système single-file performant.', en: 'Fanta AF F One heat-treated NiTi files, high-performance single-file system.' } },
  { name: { fr: 'Lime Denco', en: 'Denco File' }, brand: 'Denco', category: 'endodontie', price: 160, description: { fr: 'Limes rotatives Denco en NiTi, excellent rapport qualité-prix pour mise en forme canalaire.', en: 'Denco NiTi rotary files, excellent value for canal shaping.' } },
  { name: { fr: 'Lime iRace', en: 'iRace File' }, brand: 'FKG', category: 'endodontie', price: 350, description: { fr: 'Limes iRace FKG Dentaire, section triangulaire alternée, progression sécurisée dans le canal.', en: 'FKG iRace files, alternating triangular cross-section, safe progression through the canal.' } },
  { name: { fr: 'Lime K/H Mani', en: 'K/H Mani File' }, brand: 'Mani', category: 'endodontie', price: 80, description: { fr: 'Limes K et H Mani en acier inoxydable, qualité japonaise, haute flexibilité et résistance à la torsion.', en: 'Mani K and H stainless steel files, Japanese quality, high flexibility and torsion resistance.' } },
  { name: { fr: 'Lime K/H Gen Endo', en: 'K/H Gen Endo File' }, brand: 'Gen Endo', category: 'endodontie', price: 70, description: { fr: 'Limes K et H Gen Endo, acier inoxydable, conditionnement économique, usage cabinet courant.', en: 'Gen Endo K and H stainless steel files, economical packaging for everyday practice.' } },
  { name: { fr: 'Broche', en: 'Broach' }, brand: 'Sans Marque', category: 'endodontie', price: 55, description: { fr: 'Broches endodontiques acier pour l\'exploration et l\'élargissement initial des canaux radiculaires.', en: 'Steel endodontic broaches for exploration and initial enlargement of root canals.' } },
  { name: { fr: 'Tire Nerfs', en: 'Barbed Broach' }, brand: 'Sans Marque', category: 'endodontie', price: 45, description: { fr: 'Tire-nerfs dentaires pour extirpation pulpaire, tiges hélicoïdales acier, usage unique.', en: 'Dental barbed broaches for pulp extirpation, steel helical shafts, single use.' } },
  { name: { fr: 'R-Endo R1/R2/R3', en: 'R-Endo R1/R2/R3' }, brand: 'Micro Mega', category: 'endodontie', price: 280, description: { fr: 'Système R-Endo Micro Mega, trois limes R1/R2/R3 pour préparation canalaire progressive.', en: 'Micro Mega R-Endo system, three R1/R2/R3 files for progressive canal preparation.' } },
  { name: { fr: 'Revo Spreader', en: 'Revo Spreader' }, brand: 'Micro Mega', category: 'endodontie', price: 90, description: { fr: 'Spreader Revo Micro Mega pour compaction latérale de la gutta-percha, manche ergonomique.', en: 'Micro Mega Revo spreader for lateral gutta-percha compaction, ergonomic handle.' } },
  { name: { fr: 'Gutta Oktan 4%/6%', en: 'Oktan Gutta 4%/6%' }, brand: 'Oktan', category: 'endodontie', price: 65, description: { fr: 'Cônes de gutta-percha Oktan taper 4% ou 6%, excellente flexibilité et radio-opacité.', en: 'Oktan gutta-percha cones taper 4% or 6%, excellent flexibility and radiopacity.' } },
  { name: { fr: 'Gutta Metabiomed 4%/6%', en: 'Metabiomed Gutta 4%/6%' }, brand: 'Metabiomed', category: 'endodontie', price: 70, description: { fr: 'Cônes de gutta-percha Metabiomed taper 4% ou 6%, haute qualité, radio-opaques.', en: 'Metabiomed gutta-percha cones taper 4% or 6%, high quality, radiopaque.' } },
  { name: { fr: 'Gutta 2%', en: 'Gutta 2%' }, brand: 'Sans Marque', category: 'endodontie', price: 55, description: { fr: 'Cônes de gutta-percha standardisés ISO 2%, conditionnement économique toutes tailles.', en: 'ISO standardized 2% gutta-percha cones, economical packaging all sizes.' } },
  { name: { fr: 'Point Papier Oktan 4%/6%', en: 'Oktan Paper Point 4%/6%' }, brand: 'Oktan', category: 'endodontie', price: 55, description: { fr: 'Points papier absorbants Oktan taper 4% ou 6%, séchage canalaire précis après irrigation.', en: 'Oktan absorbent paper points taper 4% or 6%, precise canal drying after irrigation.' } },
  { name: { fr: 'Point Papier Metabiomed 4%/6%', en: 'Metabiomed Paper Point 4%/6%' }, brand: 'Metabiomed', category: 'endodontie', price: 60, description: { fr: 'Points papier absorbants Metabiomed taper 4% ou 6%, haute absorption et résistance à la déchirure.', en: 'Metabiomed absorbent paper points taper 4% or 6%, high absorption and tear resistance.' } },
  { name: { fr: 'Point Papier 2%', en: 'Paper Point 2%' }, brand: 'Sans Marque', category: 'endodontie', price: 45, description: { fr: 'Points papier absorbants ISO 2%, séchage canalaire standard, conditionnement économique.', en: 'ISO 2% absorbent paper points, standard canal drying, economical packaging.' } },
  { name: { fr: 'Carven', en: 'Carven' }, brand: 'Sans Marque', category: 'endodontie', price: 320, description: { fr: 'Solvant de gutta-percha Carven pour désobturation canalaire rapide et efficace.', en: 'Carven gutta-percha solvent for fast and effective canal obturation removal.' } },
  { name: { fr: 'Gutasol', en: 'Gutasol' }, brand: 'Sans Marque', category: 'endodontie', price: 180, description: { fr: 'Solvant de gutta-percha Gutasol à base d\'eucalyptol pour reprise de traitement endodontique.', en: 'Gutasol eucalyptol-based gutta-percha solvent for endodontic retreatment.' } },
  { name: { fr: 'Gutasolv Septadent', en: 'Gutasolv Septadent' }, brand: 'Septodont', category: 'endodontie', price: 220, description: { fr: 'Solvant de gutta-percha Gutasolv Septodont, formulation efficace pour retraitement endodontique.', en: 'Septodont Gutasolv gutta-percha solvent, effective formulation for endodontic retreatment.' } },
  { name: { fr: 'MTA Biorep', en: 'MTA Biorep' }, brand: 'Biorep', category: 'endodontie', price: 750, description: { fr: 'Ciment MTA Biorep pour réparation de perforations, coiffage pulpaire et obturation rétrograde.', en: 'Biorep MTA cement for perforation repair, pulp capping and retrograde obturation.' } },
  { name: { fr: 'Neo Sealer Flo', en: 'Neo Sealer Flo' }, brand: 'Itena', category: 'endodontie', price: 900, description: { fr: 'Ciment de scellement biocéramique injectable Neo Sealer Flo, biocompatible et hydrophile.', en: 'Neo Sealer Flo injectable bioceramic sealer, biocompatible and hydrophilic.' } },
  { name: { fr: 'Diaroot', en: 'Diaroot' }, brand: 'Meta', category: 'endodontie', price: 850, description: { fr: 'Ciment endodontique biocéramique Diaroot, excellente étanchéité apicale et biocompatibilité.', en: 'Diaroot bioceramic endodontic sealer, excellent apical seal and biocompatibility.' } },
  { name: { fr: 'Biner LC', en: 'Biner LC' }, brand: 'Itena', category: 'endodontie', price: 280, description: { fr: 'Ciment de coiffage photopolymérisable Biner LC, protection pulpaire directe et indirecte.', en: 'Biner LC light-cured capping cement, direct and indirect pulp protection.' } },
  { name: { fr: 'Metapex+', en: 'Metapex+' }, brand: 'Meta', category: 'endodontie', price: 320, description: { fr: 'Pâte de médication inter-séances Metapex+ à l\'hydroxyde de calcium et iodoforme.', en: 'Metapex+ inter-appointment medication paste with calcium hydroxide and iodoform.' } },
  { name: { fr: 'Calplus', en: 'Calplus' }, brand: 'Sans Marque', category: 'endodontie', price: 180, description: { fr: 'Hydroxyde de calcium en poudre Calplus pour médication intra-canalaire et coiffage pulpaire.', en: 'Calplus calcium hydroxide powder for intra-canal medication and pulp capping.' } },
  { name: { fr: 'Cal LC', en: 'Cal LC' }, brand: 'Sans Marque', category: 'endodontie', price: 220, description: { fr: 'Ciment à base d\'hydroxyde de calcium photopolymérisable Cal LC, coiffage indirect.', en: 'Cal LC light-cured calcium hydroxide cement, indirect pulp capping.' } },
  { name: { fr: 'Theracal LC', en: 'Theracal LC' }, brand: 'Bisco', category: 'endodontie', price: 680, description: { fr: 'Ciment de coiffage photopolymérisable Theracal LC Bisco, libération d\'ions calcium et hydroxyle.', en: 'Bisco Theracal LC light-cured capping cement, releases calcium and hydroxyl ions.' } },
  { name: { fr: 'Cortisomol', en: 'Cortisomol' }, brand: 'Septodont', category: 'endodontie', price: 280, description: { fr: 'Pâte canalaire cortico-antibiotique Cortisomol, médication d\'urgence et sédation pulpaire.', en: 'Cortisomol corticosteroid-antibiotic canal paste, emergency medication and pulp sedation.' } },
  { name: { fr: 'Endoseal', en: 'Endoseal' }, brand: 'Sans Marque', category: 'endodontie', price: 580, description: { fr: 'Ciment de scellement endodontique Endoseal, adhérence à la dentine et étanchéité apicale optimales.', en: 'Endoseal endodontic sealing cement, optimal dentin adhesion and apical seal.' } },
  { name: { fr: 'Dolo Endo Gel', en: 'Dolo Endo Gel' }, brand: 'Sans Marque', category: 'endodontie', price: 160, description: { fr: 'Gel anesthésique et analgésique Dolo Endo pour soulagement de la douleur lors des traitements canalaires.', en: 'Dolo Endo anesthetic and analgesic gel for pain relief during canal treatments.' } },
  { name: { fr: 'MD Cleanser', en: 'MD Cleanser' }, brand: 'Meta', category: 'endodontie', price: 180, description: { fr: 'Solution chélatrice MD Cleanser à l\'EDTA 17% pour élimination de la boue dentinaire.', en: 'MD Cleanser 17% EDTA chelating solution for smear layer removal.' } },
  { name: { fr: 'MD Chelcream', en: 'MD Chelcream' }, brand: 'Meta', category: 'endodontie', price: 200, description: { fr: 'Crème chélatrice MD Chelcream à l\'EDTA, lubrification et préparation canalaire facilitée.', en: 'MD Chelcream EDTA chelating cream, facilitates canal lubrication and preparation.' } },
  { name: { fr: 'EDTA 18%', en: 'EDTA 18%' }, brand: 'AT Dental', category: 'endodontie', price: 60, description: { fr: 'Solution d\'EDTA 18% pour chélation et élimination de la boue dentinaire lors de l\'irrigation canalaire.', en: '18% EDTA solution for chelation and smear layer removal during canal irrigation.' } },

  // ── CIMENT ────────────────────────────────────────────────────
  { name: { fr: 'Fuji CemOne', en: 'Fuji CemOne' }, brand: 'GC', category: 'ciment', price: 580, description: { fr: 'Ciment verre ionomère modifié résine Fuji CemOne GC, scellement en dose unitaire, prise rapide.', en: 'GC Fuji CemOne resin-modified glass ionomer cement, unit-dose delivery, fast set.' } },
  { name: { fr: 'Fuji 2 LC', en: 'Fuji 2 LC' }, brand: 'GC', category: 'ciment', price: 620, description: { fr: 'CVI modifié par résine Fuji 2 LC GC, photopolymérisable, restaurations antérieures et postérieures.', en: 'GC Fuji 2 LC resin-modified GIC, light-curable, anterior and posterior restorations.' } },
  { name: { fr: 'Ketac Molar', en: 'Ketac Molar' }, brand: '3M', category: 'ciment', price: 520, description: { fr: 'Ciment verre ionomère haute viscosité Ketac Molar 3M, restaurations postérieures de technique atraumatique.', en: '3M Ketac Molar high-viscosity glass ionomer, posterior restorations with atraumatic technique.' } },
  { name: { fr: 'Meron', en: 'Meron' }, brand: 'VOCO', category: 'ciment', price: 480, description: { fr: 'Ciment verre ionomère Meron VOCO, scellement de couronnes et bridges, excellente biocompatibilité.', en: 'VOCO Meron glass ionomer cement, crown and bridge cementation, excellent biocompatibility.' } },
  { name: { fr: 'Theracem CA', en: 'Theracem CA' }, brand: 'Sans Marque', category: 'ciment', price: 380, description: { fr: 'Ciment de scellement Theracem CA bioactif, libération d\'ions calcium, idéal pour prothèses céramiques.', en: 'Theracem CA bioactive luting cement, calcium ion release, ideal for ceramic prosthetics.' } },
  { name: { fr: 'Medifil', en: 'Medifil' }, brand: 'Sans Marque', category: 'ciment', price: 350, description: { fr: 'Ciment d\'obturation temporaire Medifil, étanchéité satisfaisante pour les obturations entre séances.', en: 'Medifil temporary filling cement, satisfactory sealing for between-session obturations.' } },
  { name: { fr: 'Medicem', en: 'Medicem' }, brand: 'Sans Marque', category: 'ciment', price: 320, description: { fr: 'Ciment de scellement provisoire Medicem au zinc, facile à éliminer, bonne résistance mécanique.', en: 'Medicem zinc provisional luting cement, easy to remove, good mechanical resistance.' } },
  { name: { fr: 'I Fil', en: 'I Fil' }, brand: 'Itena', category: 'ciment', price: 280, description: { fr: 'Ciment provisoire I Fil Itena, scellement temporaire de couronnes et inlays avec retrait facilité.', en: 'Itena I Fil provisional cement, temporary crown and inlay cementation with easy removal.' } },
  { name: { fr: 'Fuji Plus Liquid', en: 'Fuji Plus Liquid' }, brand: 'GC', category: 'ciment', price: 280, description: { fr: 'Liquide Fuji Plus Liquid GC, composant liquide pour ciment verre ionomère modifié résine.', en: 'GC Fuji Plus Liquid, liquid component for resin-modified glass ionomer cement.' } },
  { name: { fr: 'Relyx Temp', en: 'Relyx Temp' }, brand: '3M', category: 'ciment', price: 480, description: { fr: 'Ciment de scellement temporaire Relyx Temp 3M, résistance mécanique contrôlée, retrait propre.', en: '3M Relyx Temp temporary luting cement, controlled mechanical resistance, clean removal.' } },
  { name: { fr: 'NETC', en: 'NETC' }, brand: 'Sans Marque', category: 'ciment', price: 180, description: { fr: 'Ciment temporaire NETC non-eugénol, compatible avec résines composites, facile à éliminer.', en: 'NETC non-eugenol temporary cement, compatible with composite resins, easy to remove.' } },
  { name: { fr: 'Provitemp', en: 'Provitemp' }, brand: 'VOCO', category: 'ciment', price: 160, description: { fr: 'Ciment d\'obturation temporaire Provitemp, prise auto, étanchéité fiable pour obturations provisoires.', en: 'Provitemp temporary filling cement, self-setting, reliable seal for provisional obturations.' } },
  { name: { fr: 'Dentotemp', en: 'Dentotemp' }, brand: 'Sans Marque', category: 'ciment', price: 150, description: { fr: 'Ciment provisoire Dentotemp à l\'oxyde de zinc, conditionnement économique pour usage courant.', en: 'Dentotemp zinc oxide provisional cement, economical packaging for everyday use.' } },
  { name: { fr: 'Cavit 3M', en: 'Cavit 3M' }, brand: '3M', category: 'ciment', price: 280, description: { fr: 'Ciment d\'obturation temporaire Cavit 3M, prise hygroscopique, étanchéité fiable entre les séances.', en: '3M Cavit temporary filling cement, hygroscopic setting, reliable seal between sessions.' } },
  { name: { fr: 'Cavitemp', en: 'Cavitemp' }, brand: 'Sans Marque', category: 'ciment', price: 140, description: { fr: 'Ciment temporaire Cavitemp économique, obturation provisoire de courte durée entre les séances.', en: 'Economical Cavitemp temporary cement, short-term provisional obturation between sessions.' } },
  { name: { fr: 'Provis', en: 'Provis' }, brand: 'Ivoclar', category: 'ciment', price: 750, description: { fr: 'Ciment de scellement provisoire Provis Ivoclar Vivadent, non-eugénol, retrait aisé de la prothèse.', en: 'Ivoclar Vivadent Provis provisional luting cement, non-eugenol, easy prosthesis removal.' } },
  { name: { fr: 'Orafil G', en: 'Orafil G' }, brand: 'Coltene', category: 'ciment', price: 220, description: { fr: 'Ciment d\'obturation temporaire Orafil G à la gutta-percha, radio-opaque, usage endodontique et prothétique.', en: 'Coltene Orafil G gutta-percha temporary filling cement, radiopaque, endodontic and prosthetic use.' } },
  { name: { fr: 'Totalcem', en: 'Totalcem' }, brand: 'Itena', category: 'ciment', price: 580, description: { fr: 'Ciment de scellement résine dual-cure Totalcem Itena, pour couronnes, bridges et inlays céramiques.', en: 'Itena Totalcem dual-cure resin luting cement, for crowns, bridges and ceramic inlays.' } },
  { name: { fr: 'Totalceram', en: 'Totalceram' }, brand: 'Itena', category: 'ciment', price: 620, description: { fr: 'Ciment de collage céramique Totalceram Itena, translucidité optimale pour restaurations esthétiques.', en: 'Itena Totalceram ceramic bonding cement, optimal translucency for aesthetic restorations.' } },
  { name: { fr: 'Prevent Seal', en: 'Prevent Seal' }, brand: 'Sans Marque', category: 'ciment', price: 280, description: { fr: 'Vernis scellant Prevent Seal, protection des sillons et fossettes, prévention des caries occlusales.', en: 'Prevent Seal sealant varnish, pit and fissure protection, prevention of occlusal caries.' } },
  { name: { fr: 'Pulpodent', en: 'Pulpodent' }, brand: 'Septodont', category: 'ciment', price: 180, description: { fr: 'Pâte de coiffage pulpaire Pulpodent à l\'hydroxyde de calcium, protection de la pulpe exposée.', en: 'Pulpodent calcium hydroxide pulp capping paste, protection of exposed pulp.' } },
]

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI)
  console.log('MongoDB connecté')

  let added = 0
  let skipped = 0

  for (const p of newProducts) {
    const exists = await Product.findOne({ 'name.fr': p.name.fr, brand: p.brand })
    if (exists) {
      console.log(`  SKIP  ${p.name.fr} (${p.brand})`)
      skipped++
      continue
    }
    await Product.create({ ...p, inStock: true, images: [], featured: false })
    console.log(`  ADD   ${p.name.fr} (${p.brand})`)
    added++
  }

  console.log(`\nTerminé : ${added} ajoutés, ${skipped} ignorés (déjà existants)`)
  await mongoose.disconnect()
}

seed().catch((err) => { console.error(err); process.exit(1) })
